- app/src/main/java/com/framgia/forder/data/model/Image.java
- app/src/main/java/com/framgia/forder/data/model/Product.java
- app/src/main/java/com/framgia/forder/data/model/ProductResponse.java
- app/src/main/java/com/framgia/forder/data/model/Shop.java
- app/src/main/java/com/framgia/forder/data/model/ShopResponse.java
- app/src/main/java/com/framgia/forder/screen/BaseRecyclerViewAdapter.java
- app/src/main/java/com/framgia/forder/screen/mainpagetemp/mainpage/mainpagetab/ItemProductViewModel.java
- app/src/main/java/com/framgia/forder/screen/mainpagetemp/mainpage/mainpagetab/ItemShopViewModel.java
- app/src/main/java/com/framgia/forder/screen/mainpagetemp/mainpage/mainpagetab/ProductAdapter.java
- app/src/main/java/com/framgia/forder/screen/mainpagetemp/mainpage/mainpagetab/ShopAdapter.java
Redmine https://dev.framgia.com/redmine/issues/112027
Create model product,shop, adapter
> [Sprint 1] Main page-Model,adapter recyclerview

- app/src/main/java/com/framgia/forder/screen/main/MainViewModel.java
- app/src/main/java/com/framgia/forder/utils/UnSwipeViewPager.java
- app/src/main/res/color/selected_title_tab.xml
- app/src/main/res/drawable-xxhdpi/ic_cart_selected.xml
- app/src/main/res/drawable-xxhdpi/ic_home_selected.xml
- app/src/main/res/drawable-xxhdpi/ic_notifications_selected.xml
- app/src/main/res/drawable-xxhdpi/ic_person_selected.xml
- app/src/main/res/drawable-xxhdpi/ic_search_selected.xml
- app/src/main/res/drawable/selected_ic_cart.xml
- app/src/main/res/drawable/selected_ic_home.xml
- app/src/main/res/drawable/selected_ic_notifications.xml
- app/src/main/res/drawable/selected_ic_profile.xml
- app/src/main/res/drawable/selected_ic_search.xml
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/layout_footer.xml
- app/src/main/res/values/styles.xml
https://dev.framgia.com/redmine/users/1671
Disable swipte viewpager
> [Sprint 1] Disable swipte viewpager

- app/src/main/java/com/framgia/forder/data/source/UserDataSource.java
- app/src/main/java/com/framgia/forder/data/source/UserRepository.java
- app/src/main/java/com/framgia/forder/data/source/local/UserLocalDataSource.java
- app/src/main/java/com/framgia/forder/data/source/local/sharedprf/SharedPrefsKey.java
- app/src/main/java/com/framgia/forder/data/source/remote/UserRemoteDataSource.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/middleware/RetrofitInterceptor.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/middleware/RxErrorHandlingCallAdapterFactory.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/service/FOrderServiceClient.java
- app/src/main/java/com/framgia/forder/screen/login/LoginPresenter.java
> Update Header Retrofit

- app/src/main/java/com/framgia/forder/data/model/ShoppingCart.java
- app/src/main/java/com/framgia/forder/data/source/ProductDataSource.java
- app/src/main/java/com/framgia/forder/data/source/ProductRepository.java
- app/src/main/java/com/framgia/forder/data/source/local/ProductLocalDataSource.java
- app/src/main/java/com/framgia/forder/data/source/local/realm/BaseLocalDataSource.java
- app/src/main/java/com/framgia/forder/screen/mainpage/MainPageContract.java
- app/src/main/java/com/framgia/forder/screen/mainpage/MainPageFragment.java
- app/src/main/java/com/framgia/forder/screen/mainpage/MainPagePresenter.java
- app/src/main/java/com/framgia/forder/screen/mainpage/MainPageViewModel.java
- app/src/main/java/com/framgia/forder/utils/Constant.java
https://dev.framgia.com/redmine/issues/112994
Add product to cart
> [Sprint 2] Add product to cart

- app/src/main/java/com/framgia/forder/screen/main/FragmentContainer.java
- app/src/main/java/com/framgia/forder/screen/searchpage/SearchContainerAdapter.java
- app/src/main/java/com/framgia/forder/screen/searchpage/SearchContainerContract.java
- app/src/main/java/com/framgia/forder/screen/searchpage/SearchContainerFragment.java
- app/src/main/java/com/framgia/forder/screen/searchpage/SearchContainerPresenter.java
- app/src/main/java/com/framgia/forder/screen/searchpage/SearchContainerViewModel.java
- app/src/main/res/layout/fragment_search_container.xml
- app/src/main/res/menu/menu_search.xml
- app/src/main/res/values/strings.xml
> [Sprint 2]Feature create ui search

- app/src/main/java/com/framgia/forder/screen/listProduct/ListProductContract.java
- app/src/main/java/com/framgia/forder/screen/listProduct/ListProductFragment.java
- app/src/main/java/com/framgia/forder/screen/listProduct/ListProductPresenter.java
- app/src/main/java/com/framgia/forder/screen/listProduct/ListProductViewModel.java
- app/src/main/java/com/framgia/forder/screen/mainpage/MainPageViewModel.java
- app/src/main/res/drawable/border_item.xml
- app/src/main/res/layout/fragment_listproduct.xml
- app/src/main/res/layout/fragment_main_page.xml
List All Product
Link redmine : https://dev.framgia.com/redmine/issues/113296
Task : Create UI List All Product
Affect : mainPage
> [Sprint 2] Feature UI List Product

- app/src/main/res/layout/fragment_shoppingcart.xml
- app/src/main/res/layout/item_content_cart.xml
- app/src/main/res/values/strings.xml
https://dev.framgia.com/redmine/issues/112994
Fix ui Cart
Effect : None
> [Sprint 2] Fix ui Cart

- .gitignore
- app/src/main/java/com/framgia/forder/screen/chooseDomain/ChooseDomainViewModel.java
- app/src/main/java/com/framgia/forder/screen/main/MainActivity.java
- app/src/main/java/com/framgia/forder/screen/main/MainContainerFragment.java
- app/src/main/java/com/framgia/forder/screen/main/MainContract.java
- app/src/main/java/com/framgia/forder/screen/main/MainViewModel.java
- app/src/main/java/com/framgia/forder/screen/main/MainViewPagerAdapter.java
- app/src/main/java/com/framgia/forder/utils/Constant.java
- app/src/main/java/com/framgia/forder/utils/navigator/Navigator.java
- app/src/main/res/values/strings.xml
- Handle action back on MainActivity
- Change Base URL
- Update .gitignore
- Fix crash choose domain
> Handle action back on MainActivity

- app/src/main/java/com/framgia/forder/data/source/ShopDataSource.java
- app/src/main/java/com/framgia/forder/data/source/ShopRepository.java
- app/src/main/java/com/framgia/forder/data/source/remote/ShopRemoteDataSource.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/service/FOrderApi.java
- app/src/main/java/com/framgia/forder/screen/mainpage/MainPageContract.java
- app/src/main/java/com/framgia/forder/screen/mainpage/MainPageFragment.java
- app/src/main/java/com/framgia/forder/screen/mainpage/MainPagePresenter.java
- app/src/main/java/com/framgia/forder/screen/mainpage/MainPageViewModel.java
- app/src/main/res/layout/fragment_main_page.xml
- app/src/main/res/layout/item_shop.xml
[Sprint 2] Main page-load data
Link redmine : https://dev.framgia.com/redmine/issues/113277
Task : Load list shop
Affect : mainPage
> [Sprint 2] Main page-load shop

- app/src/main/java/com/framgia/forder/screen/searchpage/SearchContainerAdapter.java
- app/src/main/java/com/framgia/forder/screen/searchproduct/ProductSearchResultContract.java
- app/src/main/java/com/framgia/forder/screen/searchproduct/ProductSearchResultFragment.java
- app/src/main/java/com/framgia/forder/screen/searchproduct/ProductSearchResultPresenter.java
- app/src/main/java/com/framgia/forder/screen/searchproduct/ProductSearchResultViewModel.java
- app/src/main/java/com/framgia/forder/screen/searchshop/ShopSearchResultContract.java
- app/src/main/java/com/framgia/forder/screen/searchshop/ShopSearchResultFragment.java
- app/src/main/java/com/framgia/forder/screen/searchshop/ShopSearchResultPresenter.java
- app/src/main/java/com/framgia/forder/screen/searchshop/ShopSearchResultViewModel.java
- app/src/main/res/layout/fragment_product_search_result.xml
- app/src/main/res/layout/fragment_search_container.xml
- app/src/main/res/layout/fragment_shop_search_result.xml
- Link redmine: https://dev.framgia.com/redmine/issues/113283
- Finish create ui search
- None
> [Sprint 2]Finish create ui search

- app/src/main/java/com/framgia/forder/data/model/ShoppingCart.java
- app/src/main/java/com/framgia/forder/data/source/local/ProductLocalDataSource.java
- app/src/main/java/com/framgia/forder/screen/mainpage/MainPageContract.java
- app/src/main/java/com/framgia/forder/screen/mainpage/MainPagePresenter.java
- app/src/main/java/com/framgia/forder/screen/mainpage/MainPageViewModel.java
- https://dev.framgia.com/redmine/issues/112994
- Fix add product to cart 
> [Sprint 2] Fix add product to cart 

- app/src/main/java/com/framgia/forder/data/source/DomainDataSource.java
- app/src/main/java/com/framgia/forder/data/source/DomainRepository.java
- app/src/main/java/com/framgia/forder/data/source/local/DomainLocalDataSource.java
- app/src/main/java/com/framgia/forder/data/source/local/sharedprf/SharedPrefsKey.java
- app/src/main/java/com/framgia/forder/screen/chooseDomain/ChooseDomainContract.java
- app/src/main/java/com/framgia/forder/screen/chooseDomain/ChooseDomainPresenter.java
- app/src/main/java/com/framgia/forder/screen/chooseDomain/ChooseDomainViewModel.java
- app/src/main/java/com/framgia/forder/screen/mainpage/MainPagePresenter.java
- app/src/main/java/com/framgia/forder/screen/splash/SplashActivity.java
Redmine https://dev.framgia.com/redmine/issues/113668
Fix Domain data source
> [Sprint 2] Feature change domain- fix data domain

- app/src/main/java/com/framgia/forder/data/source/remote/ProductRemoteDataSource.java
- app/src/main/java/com/framgia/forder/screen/listProduct/ListProductContract.java
- app/src/main/java/com/framgia/forder/screen/listProduct/ListProductFragment.java
- app/src/main/java/com/framgia/forder/screen/listProduct/ListProductPresenter.java
- app/src/main/java/com/framgia/forder/screen/listProduct/ListProductViewModel.java
- app/src/main/java/com/framgia/forder/screen/mainpage/MainPageFragment.java
- app/src/main/java/com/framgia/forder/screen/mainpage/MainPagePresenter.java
- app/src/main/java/com/framgia/forder/screen/mainpage/MainPageViewModel.java
- app/src/main/java/com/framgia/forder/utils/binding/LayoutManagers.java
- app/src/main/res/layout/fragment_listproduct.xml
List All Product
Link redmine : https://dev.framgia.com/redmine/issues/113296
Task : Logic List All Product
Affect : mainPage
> [Sprint 2] Feature Logic Product List

- app/src/main/java/com/framgia/forder/screen/main/MainActivity.java
- app/src/main/java/com/framgia/forder/screen/main/MainContract.java
- app/src/main/java/com/framgia/forder/screen/main/MainPresenter.java
- app/src/main/java/com/framgia/forder/screen/main/MainViewModel.java
- app/src/main/res/values/strings.xml
Redmine https://dev.framgia.com/redmine/issues/113668
Feature change domain
> [Sprint 2] Feature change domain

- app/src/main/java/com/framgia/forder/data/model/Shop.java
- app/src/main/java/com/framgia/forder/data/model/User.java
- app/src/main/java/com/framgia/forder/data/source/SearchDataSource.java
- app/src/main/java/com/framgia/forder/data/source/SearchRepository.java
- app/src/main/java/com/framgia/forder/data/source/remote/SearchRemoteDataSource.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/response/SearchResponse.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/service/FOrderApi.java
- app/src/main/java/com/framgia/forder/screen/searchpage/SearchContainerAdapter.java
- app/src/main/java/com/framgia/forder/screen/searchpage/SearchContainerContract.java
- app/src/main/java/com/framgia/forder/screen/searchpage/SearchContainerFragment.java
- app/src/main/java/com/framgia/forder/screen/searchpage/SearchContainerPresenter.java
- app/src/main/java/com/framgia/forder/screen/searchpage/SearchContainerViewModel.java
- app/src/main/java/com/framgia/forder/screen/searchproduct/ProductSearchResultFragment.java
- app/src/main/java/com/framgia/forder/screen/searchshop/ShopSearchResultFragment.java
Feature logic search 
Link redmine: https://dev.framgia.com/redmine/issues/113283
Task: Logic search
> [Sprint 2]feature logic search

- app/src/main/java/com/framgia/forder/data/source/remote/ShopRemoteDataSource.java
- app/src/main/java/com/framgia/forder/screen/listshop/ListShopContract.java
- app/src/main/java/com/framgia/forder/screen/listshop/ListShopFragment.java
- app/src/main/java/com/framgia/forder/screen/listshop/ListShopPresenter.java
- app/src/main/java/com/framgia/forder/screen/listshop/ListShopViewModel.java
- app/src/main/java/com/framgia/forder/screen/mainpage/MainPagePresenter.java
- app/src/main/res/layout/fragment_list_shop.xml
- app/src/main/res/values/strings.xml
Link redmine: https://dev.framgia.com/redmine/issues/113701
Task: List all shop
Effect: N/A
> [Sprint 2] List all shop ui

- app/src/main/java/com/framgia/forder/screen/searchproduct/ProductSearchResultContract.java
- app/src/main/java/com/framgia/forder/screen/searchproduct/ProductSearchResultFragment.java
- app/src/main/java/com/framgia/forder/screen/searchproduct/ProductSearchResultViewModel.java
- app/src/main/java/com/framgia/forder/screen/searchshop/ShopSearchResultContract.java
- app/src/main/java/com/framgia/forder/screen/searchshop/ShopSearchResultFragment.java
- app/src/main/java/com/framgia/forder/screen/searchshop/ShopSearchResultViewModel.java
- app/src/main/res/layout/fragment_product_search_result.xml
- app/src/main/res/layout/fragment_search_container.xml
- app/src/main/res/layout/fragment_shop_search_result.xml
- app/src/main/res/menu/menu_search.xml
Feature logic search next
Link redmine: https://dev.framgia.com/redmine/issues/113283
Task: Logic search
> Feature logic search next

- app/src/main/java/com/framgia/forder/data/model/CartItem.java
- app/src/main/java/com/framgia/forder/data/source/local/ProductLocalDataSource.java
- app/src/main/java/com/framgia/forder/screen/cart/ItemShoppingCartViewModel.java
- app/src/main/java/com/framgia/forder/screen/cart/ShoppingCartAdapter.java
- app/src/main/java/com/framgia/forder/screen/cart/ShoppingCartContract.java
- app/src/main/java/com/framgia/forder/screen/cart/ShoppingCartFragment.java
- app/src/main/java/com/framgia/forder/screen/cart/ShoppingCartPresenter.java
- app/src/main/java/com/framgia/forder/screen/cart/ShoppingCartViewModel.java
- app/src/main/res/layout/fragment_shoppingcart.xml
- app/src/main/res/layout/item_content_cart.xml
- app/src/main/res/layout/item_header_cart.xml
https://dev.framgia.com/redmine/issues/112994
Logic List Order
Effect : None
> [Sprint 2] Logic List Order

- app/src/main/java/com/framgia/forder/screen/listshop/ListShopAdapter.java
- app/src/main/java/com/framgia/forder/screen/listshop/ListShopContract.java
- app/src/main/java/com/framgia/forder/screen/listshop/ListShopFragment.java
- app/src/main/java/com/framgia/forder/screen/listshop/ListShopPresenter.java
- app/src/main/java/com/framgia/forder/screen/listshop/ListShopViewModel.java
- app/src/main/java/com/framgia/forder/screen/mainpage/MainPageViewModel.java
- app/src/main/java/com/framgia/forder/screen/mainpage/shop/ItemShopViewModel.java
- app/src/main/res/layout/fragment_list_shop.xml
- app/src/main/res/layout/fragment_main_page.xml
- app/src/main/res/layout/item_header_shop.xml
- app/src/main/res/layout/item_list_shop.xml
- app/src/main/res/values/strings.xml
Redmine link : https://dev.framgia.com/redmine/issues/113701
Task: List all shop
Effect: N/A
> [Sprint 2] List all shop

- app/src/main/java/com/framgia/forder/screen/searchshop/ShopSearchResultAdapter.java
- app/src/main/java/com/framgia/forder/screen/searchshop/ShopSearchResultFragment.java
- app/src/main/java/com/framgia/forder/screen/searchshop/ShopSearchResultViewModel.java
- app/src/main/res/drawable/border_spinner.xml
Feature logic search final
Link redmine: https://dev.framgia.com/redmine/issues/113283
Task: Logic search
> [Sprint 2]Feature logic search final

- app/src/main/java/com/framgia/forder/screen/listProduct/ListProductFragment.java
- app/src/main/java/com/framgia/forder/screen/listProduct/ListProductViewModel.java
- app/src/main/java/com/framgia/forder/screen/listProduct/adapter/ListProductAdapter.java
- app/src/main/java/com/framgia/forder/screen/mainpage/product/ProductAdapter.java
- app/src/main/res/drawable/boder_item_product.xml
- app/src/main/res/layout/fragment_listproduct.xml
- app/src/main/res/layout/item_header_product.xml
- app/src/main/res/layout/item_list_product.xml
- app/src/main/res/values-sw360dp/dimens.xml
- app/src/main/res/values/colors.xml
List All Product
Link redmine : https://dev.framgia.com/redmine/issues/113296
Task : Logic Header List All Product
> [Sprint 2] Feature Header List

- app/src/main/java/com/framgia/forder/screen/searchproduct/ProductSearchResultAdapter.java
- app/src/main/java/com/framgia/forder/screen/searchproduct/ProductSearchResultFragment.java
- app/src/main/java/com/framgia/forder/screen/searchproduct/ProductSearchResultViewModel.java
- app/src/main/res/layout/fragment_product_search_result.xml
Feature logic search fix layout 
Link redmine: https://dev.framgia.com/redmine/issues/113283
Task: fix ui load product search
> [Sprint 2]Feature logic search fix layout

- app/src/main/java/com/framgia/forder/data/model/Notification.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/response/NotificationRespone.java
- app/src/main/java/com/framgia/forder/screen/main/MainContainerFragment.java
- app/src/main/java/com/framgia/forder/screen/notification/NotificationPageAdapter.java
- app/src/main/java/com/framgia/forder/screen/notification/NotificationPageContract.java
- app/src/main/java/com/framgia/forder/screen/notification/NotificationPageFragment.java
- app/src/main/java/com/framgia/forder/screen/notification/NotificationPagePresenter.java
- app/src/main/java/com/framgia/forder/screen/notification/NotificationPageViewModel.java
- app/src/main/res/layout/fragment_list_notification.xml
- app/src/main/res/layout/item_list_notification.xml
Link redmine: https://dev.framgia.com/redmine/issues/114168
Task: List notification
Effect: N/A
> [Sprint 3] List notification ui

- app/src/main/java/com/framgia/forder/data/model/ShoppingCart.java
- app/src/main/java/com/framgia/forder/data/source/ProductDataSource.java
- app/src/main/java/com/framgia/forder/data/source/ProductRepository.java
- app/src/main/java/com/framgia/forder/data/source/local/ProductLocalDataSource.java
- app/src/main/java/com/framgia/forder/screen/cart/ShoppingCartFragment.java
- app/src/main/java/com/framgia/forder/screen/cart/ShoppingCartPresenter.java
- app/src/main/java/com/framgia/forder/screen/cart/ShoppingCartViewModel.java
- app/src/main/java/com/framgia/forder/screen/listProduct/ListProductFragment.java
- app/src/main/java/com/framgia/forder/screen/listProduct/ListProductPresenter.java
- app/src/main/java/com/framgia/forder/screen/mainpage/MainPageFragment.java
- app/src/main/java/com/framgia/forder/screen/mainpage/MainPagePresenter.java
- app/src/main/java/com/framgia/forder/screen/productdetail/ProductDetailFragment.java
- app/src/main/res/drawable/ic_delete.xml
- app/src/main/res/layout/fragment_shoppingcart.xml
- app/src/main/res/layout/item_header_cart.xml
- app/src/main/res/values/strings.xml
- https://dev.framgia.com/redmine/issues/114081
- Fix logic list order
> [Sprint 3] Fix logic list order

- app/src/main/java/com/framgia/forder/screen/main/MainViewModel.java
- app/src/main/java/com/framgia/forder/screen/main/MainViewPagerAdapter.java
- app/src/main/java/com/framgia/forder/screen/mainpage/MainPageContainerAdapter.java
- app/src/main/java/com/framgia/forder/screen/mainpage/MainPageContainerContract.java
- app/src/main/java/com/framgia/forder/screen/mainpage/MainPageContainerFragment.java
- app/src/main/java/com/framgia/forder/screen/mainpage/MainPageContainerViewModel.java
- app/src/main/java/com/framgia/forder/utils/navigator/Navigator.java
Redmine https://dev.framgia.com/redmine/issues/113668
Change domain reload data
> [Sprint 2] Function change domain-reload data

- app/src/main/java/com/framgia/forder/data/source/NotificationDataSource.java
- app/src/main/java/com/framgia/forder/data/source/NotificationRepository.java
- app/src/main/java/com/framgia/forder/data/source/remote/NotificationRemoteDataSource.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/response/NotificationResponse.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/service/FOrderApi.java
- app/src/main/java/com/framgia/forder/screen/notification/NotificationPageFragment.java
- app/src/main/java/com/framgia/forder/screen/notification/NotificationPagePresenter.java
- app/src/main/java/com/framgia/forder/screen/notification/NotificationPageViewModel.java
Link redmine: https://dev.framgia.com/redmine/issues/114168
Task: List notification
Effect: N/A
> [Sprint 3] Logic list notification

- app/src/main/java/com/framgia/forder/screen/cart/ShoppingCartContract.java
- app/src/main/java/com/framgia/forder/screen/cart/ShoppingCartFragment.java
- app/src/main/java/com/framgia/forder/screen/cart/ShoppingCartPresenter.java
- app/src/main/java/com/framgia/forder/screen/cart/ShoppingCartViewModel.java
- app/src/main/java/com/framgia/forder/screen/listProduct/ListProductContract.java
- app/src/main/java/com/framgia/forder/screen/listProduct/ListProductPresenter.java
- app/src/main/java/com/framgia/forder/screen/listProduct/ListProductViewModel.java
- app/src/main/java/com/framgia/forder/screen/listProduct/adapter/ListProductAdapter.java
- app/src/main/java/com/framgia/forder/screen/main/MainContainerFragment.java
- https://dev.framgia.com/redmine/issues/114081
- Fix logic list order final
> [Sprint 3] Fix logic list order final

- app/src/main/java/com/framgia/forder/data/model/CollectionAvatar.java
- app/src/main/java/com/framgia/forder/data/model/Notification.java
- app/src/main/java/com/framgia/forder/data/source/NotificationRepository.java
- app/src/main/java/com/framgia/forder/screen/notification/NotificationPagePresenter.java
- app/src/main/java/com/framgia/forder/widgets/CircleImageView.java
- app/src/main/res/layout/fragment_profile.xml
- app/src/main/res/layout/item_list_notification.xml
- app/src/main/res/values/attrs.xml
- app/src/main/res/values/strings.xml
Link redmine:
Task: list notification
Effect: N/A
> [Sprint 3] Fake data notification

- app/src/main/java/com/framgia/forder/data/source/ProductDataSource.java
- app/src/main/java/com/framgia/forder/data/source/ProductRepository.java
- app/src/main/java/com/framgia/forder/data/source/local/ProductLocalDataSource.java
- app/src/main/java/com/framgia/forder/screen/cart/ItemShoppingCartViewModel.java
- app/src/main/java/com/framgia/forder/screen/cart/OrderItemListener.java
- app/src/main/java/com/framgia/forder/screen/cart/ShoppingCartContract.java
- app/src/main/java/com/framgia/forder/screen/cart/ShoppingCartPresenter.java
- app/src/main/java/com/framgia/forder/screen/cart/ShoppingCartViewModel.java
- https://dev.framgia.com/redmine/issues/114091
- Logic order
> [Sprint 3] Logic order

- app/src/main/java/com/framgia/forder/data/source/ShopDataSource.java
- app/src/main/java/com/framgia/forder/data/source/ShopRepository.java
- app/src/main/java/com/framgia/forder/data/source/remote/ShopRemoteDataSource.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/service/FOrderApi.java
- app/src/main/java/com/framgia/forder/screen/shopDetail/ShopDetailPresenter.java
- app/src/main/res/layout/fragment_shop_detail.xml
Feature logic shop detail next
Link redmine: https://dev.framgia.com/redmine/issues/114085
Task: Detail Shop
Effect: N/A
> [Sprint 3]Feature logic shop detail next

- app/build.gradle
- app/src/main/java/com/framgia/forder/screen/searchpage/SearchContainerFragment.java
- app/src/main/java/com/framgia/forder/screen/searchpage/SearchContainerViewModel.java
- app/src/main/java/com/framgia/forder/screen/searchproduct/ProductSearchResultFragment.java
- app/src/main/java/com/framgia/forder/screen/searchshop/ShopSearchResultFragment.java
- app/src/main/java/com/framgia/forder/screen/searchshop/ShopSearchResultViewModel.java
- app/src/main/res/layout/fragment_main_page_container.xml
- app/src/main/res/layout/fragment_search_container.xml
- app/src/main/res/layout/fragment_shop_detail.xml
- app/src/main/res/values-sw360dp/dimens.xml
- app/src/main/res/values/strings.xml
- dependencies.gradle
Fix ui search
Task: Search
Effect: N/A
> [Sprint 3]Fix ui search

- app/src/main/java/com/framgia/forder/data/model/Order.java
- app/src/main/java/com/framgia/forder/data/model/OrderDetail.java
- app/src/main/java/com/framgia/forder/screen/ordermanagement/checkorder/CheckOrderAdapter.java
- app/src/main/java/com/framgia/forder/screen/ordermanagement/checkorder/ItemCheckOrderViewModel.java
- app/src/main/java/com/framgia/forder/screen/ordermanagement/checkorder/ItemParentCheckOrderViewModel.java
- app/src/main/java/com/framgia/forder/utils/Constant.java
- app/src/main/res/layout/item_check_order.xml
- app/src/main/res/layout/item_parent_check_order.xml
- app/src/main/res/values/strings.xml
Redmine https://dev.framgia.com/redmine/issues/114364
Check order databinding
> [Sprint 3] Order managememnt-check order databinding

- app/src/main/java/com/framgia/forder/data/model/Cart.java
- app/src/main/java/com/framgia/forder/data/model/CartItem.java
- app/src/main/java/com/framgia/forder/data/source/ProductDataSource.java
- app/src/main/java/com/framgia/forder/data/source/ProductRepository.java
- app/src/main/java/com/framgia/forder/data/source/local/ProductLocalDataSource.java
- app/src/main/java/com/framgia/forder/data/source/remote/ProductRemoteDataSource.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/request/OrderRequest.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/response/OrderResponse.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/service/FOrderApi.java
- app/src/main/java/com/framgia/forder/screen/cart/ShoppingCartPresenter.java
- app/src/main/java/com/framgia/forder/utils/Utils.java
- https://dev.framgia.com/redmine/issues/114091
- Feature logic order final
> [Sprint 3] Feature Logic order final

- app/src/main/java/com/framgia/forder/screen/orderhistory/OrderHistoryAdapter.java
- app/src/main/java/com/framgia/forder/screen/orderhistory/OrderHistoryContract.java
- app/src/main/java/com/framgia/forder/screen/orderhistory/OrderHistoryFragment.java
- app/src/main/java/com/framgia/forder/screen/orderhistory/OrderHistoryPresenter.java
- app/src/main/java/com/framgia/forder/screen/orderhistory/OrderHistoryViewModel.java
- app/src/main/java/com/framgia/forder/screen/profilepage/ProfilePageViewModel.java
- app/src/main/res/drawable/ic_arrow_back_white.xml
- app/src/main/res/drawable/ic_filter_list_white.xml
- app/src/main/res/drawable/img_header_profile.xml
- app/src/main/res/layout/fragment_order_history.xml
- app/src/main/res/layout/item_order_history.xml
- app/src/main/res/values/strings.xml
Link redmind: https://dev.framgia.com/redmine/issues/114363
Task: List order
Effect: Logic list order
> [Sprint 3] List order history ui

- app/src/main/java/com/framgia/forder/data/source/OrderDataSource.java
- app/src/main/java/com/framgia/forder/data/source/OrderRepository.java
- app/src/main/java/com/framgia/forder/data/source/remote/OrderRemoteDataSource.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/response/OrderManagementResponse.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/service/FOrderApi.java
- app/src/main/java/com/framgia/forder/screen/ordermanagement/checkorder/CheckOrderAdapter.java
- app/src/main/java/com/framgia/forder/screen/ordermanagement/checkorder/CheckOrderContract.java
- app/src/main/java/com/framgia/forder/screen/ordermanagement/checkorder/CheckOrderFragment.java
- app/src/main/java/com/framgia/forder/screen/ordermanagement/checkorder/CheckOrderPresenter.java
- app/src/main/java/com/framgia/forder/screen/ordermanagement/checkorder/CheckOrderViewModel.java
Redmine https://dev.framgia.com/redmine/issues/114364
Check order logic
> [Sprint 3] Order management-Check order logic

- app/src/main/java/com/framgia/forder/data/model/Order.java
- app/src/main/java/com/framgia/forder/screen/orderhistory/ItemHeaderOrderHistoryViewModel.java
- app/src/main/java/com/framgia/forder/screen/orderhistory/ItemOrderHistoryViewModel.java
- app/src/main/java/com/framgia/forder/screen/orderhistory/OrderHistoryAdapter.java
- app/src/main/java/com/framgia/forder/screen/orderhistory/OrderHistoryFragment.java
- app/src/main/java/com/framgia/forder/screen/orderhistory/OrderHistoryViewModel.java
- app/src/main/java/com/framgia/forder/utils/Constant.java
- app/src/main/java/com/framgia/forder/utils/OrderStatusCode.java
- app/src/main/java/com/framgia/forder/utils/Utils.java
- app/src/main/java/com/framgia/forder/widgets/dialog/DialogManager.java
- app/src/main/res/layout/fragment_order_history.xml
- app/src/main/res/layout/item_header_order_history.xml
- app/src/main/res/layout/item_order_history.xml
Link redmine: https://dev.framgia.com/redmine/issues/114363
Task: List order history
Effect: N/A
> [Sprint 3] Feature list order history logic

- circle.yml
- scripts/saddler.sh
> CI comment

- scripts/saddler.sh
> Fix ci comment

- app/src/main/java/com/framgia/forder/data/source/OrderRepository.java
- app/src/main/java/com/framgia/forder/screen/ordermanagement/OrderManagementActivity.java
- app/src/main/java/com/framgia/forder/screen/ordermanagement/OrderManagementViewModel.java
- app/src/main/java/com/framgia/forder/screen/ordermanagement/checkorder/ItemCheckOrderViewModel.java
- app/src/main/java/com/framgia/forder/screen/profilepage/ProfilePageViewModel.java
- app/src/main/java/com/framgia/forder/utils/navigator/Navigator.java
- app/src/main/res/layout/activity_order_management.xml
- app/src/main/res/layout/fragment_check_order.xml
- app/src/main/res/layout/item_parent_check_order.xml
- app/src/main/res/values/strings.xml
Redmine https://dev.framgia.com/redmine/issues/114364
Get list order management
> [Sprint 3] Order management-Feature get list order

- app/src/main/java/com/framgia/forder/data/source/DomainRepository.java
- app/src/main/java/com/framgia/forder/data/source/OrderDataSource.java
- app/src/main/java/com/framgia/forder/data/source/OrderRepository.java
- app/src/main/java/com/framgia/forder/data/source/remote/OrderRemoteDataSource.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/response/OrderResponse.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/service/FOrderApi.java
- app/src/main/java/com/framgia/forder/screen/orderhistory/OrderHistoryFragment.java
- app/src/main/java/com/framgia/forder/screen/orderhistory/OrderHistoryPresenter.java
- app/src/main/res/layout/item_header_order_history.xml
- app/src/main/res/layout/item_order_history.xml
Link redmine: https://dev.framgia.com/redmine/issues/114363
Task: List order history
Effect: N/A
> [Sprint 3] Logic list order history

- app/src/main/java/com/framgia/forder/data/source/ShopDataSource.java
- app/src/main/java/com/framgia/forder/data/source/ShopRepository.java
- app/src/main/java/com/framgia/forder/data/source/remote/ShopRemoteDataSource.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/service/FOrderApi.java
- app/src/main/java/com/framgia/forder/screen/shopmanagement/adapter/ListShopManagementAdapter.java
- app/src/main/res/layout/item_shop_management.xml
Feature Logic Get Data List Shop Management
Link redmine : https://dev.framgia.com/redmine/issues/115453
Task : List Shop Management
Effect: N/A
> [Sprint 4] Feature Logic Get Data List Shop Management

- app/src/main/java/com/framgia/forder/data/model/Shop.java
- app/src/main/java/com/framgia/forder/data/model/ShopManagement.java
- app/src/main/java/com/framgia/forder/data/source/ShopDataSource.java
- app/src/main/java/com/framgia/forder/data/source/ShopRepository.java
- app/src/main/java/com/framgia/forder/data/source/remote/ShopRemoteDataSource.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/response/ShopManagementResponse.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/service/FOrderApi.java
- app/src/main/java/com/framgia/forder/screen/productdetail/ProductDetailViewModel.java
- app/src/main/java/com/framgia/forder/screen/shopmanagement/ItemShopManagementViewModel.java
- app/src/main/java/com/framgia/forder/screen/shopmanagement/ListShopManagementAdapter.java
- app/src/main/java/com/framgia/forder/screen/shopmanagement/ShopManagementContract.java
- app/src/main/java/com/framgia/forder/screen/shopmanagement/ShopManagementFragment.java
- app/src/main/java/com/framgia/forder/screen/shopmanagement/ShopManagementPresenter.java
- app/src/main/java/com/framgia/forder/screen/shopmanagement/ShopManagementViewModel.java
- app/src/main/res/layout/fragment_shopmanagement.xml
- app/src/main/res/layout/item_shop_management.xml
Feature Logic Load Data List Shop Management
Link redmine : https://dev.framgia.com/redmine/issues/115453
Task : List Shop Management
Effect: N/A
> [Sprint 4] Feature Logic Load Data List Shop Management

- app/src/main/java/com/framgia/forder/data/model/ShopInfo.java
- app/src/main/java/com/framgia/forder/data/model/ShopManagement.java
- app/src/main/java/com/framgia/forder/screen/shopmanagement/ItemShopInfoViewModel.java
- app/src/main/java/com/framgia/forder/screen/shopmanagement/ItemShopManagementViewModel.java
- app/src/main/java/com/framgia/forder/screen/shopmanagement/ListShopManagementAdapter.java
- app/src/main/java/com/framgia/forder/screen/shopmanagement/ShopManagementFragment.java
- app/src/main/java/com/framgia/forder/screen/shopmanagement/ShopManagementViewModel.java
- app/src/main/res/layout/fragment_shopmanagement.xml
- app/src/main/res/layout/item_join_domain.xml
- app/src/main/res/layout/item_shop_management.xml
- app/src/main/res/values/strings.xml
Feature Get List Shop Info
Link redmine : https://dev.framgia.com/redmine/issues/116010
Task : Join Domain Shop Management
Effect: N/A
> [Sprint 4] Feature Logic Load ShopInfo

- app/src/main/java/com/framgia/forder/data/model/Domain.java
- app/src/main/java/com/framgia/forder/data/model/ShopManagement.java
- app/src/main/java/com/framgia/forder/screen/shopmanagement/ItemShopInfoViewModel.java
- app/src/main/java/com/framgia/forder/screen/shopmanagement/ListShopManagementAdapter.java
- app/src/main/java/com/framgia/forder/utils/binding/BindingUtils.java
- app/src/main/res/drawable/border_pedding.xml
- app/src/main/res/drawable/border_status.xml
- app/src/main/res/drawable/ic_local_dining_24dp.xml
- app/src/main/res/drawable/ic_people_24dp.xml
- app/src/main/res/drawable/ic_store_24dp.xml
- app/src/main/res/layout/fragment_shopmanagement.xml
- app/src/main/res/layout/item_join_domain.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/strings.xml
Feature Join Domain Shop Management
Link redmine : https://dev.framgia.com/redmine/issues/116010
Task : Join Domain Shop Management
Effect: N/A
> [Sprint 4] Feature Join Domain Shop Management

- app/src/main/java/com/framgia/forder/data/source/ShopDataSource.java
- app/src/main/java/com/framgia/forder/data/source/ShopRepository.java
- app/src/main/java/com/framgia/forder/data/source/remote/ShopRemoteDataSource.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/request/ApplyShopToDomainRequest.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/request/LeaveShopToDomainRequest.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/service/FOrderApi.java
- app/src/main/java/com/framgia/forder/screen/shopmanagement/ItemShopInfoViewModel.java
- app/src/main/java/com/framgia/forder/screen/shopmanagement/ListShopManagementAdapter.java
- app/src/main/java/com/framgia/forder/screen/shopmanagement/ShopManagementContract.java
- app/src/main/java/com/framgia/forder/screen/shopmanagement/ShopManagementPresenter.java
- app/src/main/java/com/framgia/forder/screen/shopmanagement/ShopManagementViewModel.java
- app/src/main/res/values/strings.xml
Feature Logic Request And Cancel Shop In Domain
Link redmine : https://dev.framgia.com/redmine/issues/116010
Task : Join Domain Shop Management
Effect: N/A
> [Sprint 4] Feature Logic Request And Cancel Shop In Domain

- app/src/main/java/com/framgia/forder/screen/shopinfo/ShopInformationPageAdapter.java
- app/src/main/java/com/framgia/forder/screen/shopinfo/ShopInformationPageContainerContract.java
- app/src/main/java/com/framgia/forder/screen/shopinfo/ShopInformationPageContainerFragment.java
- app/src/main/java/com/framgia/forder/screen/shopinfo/ShopInformationPageContainerPresenter.java
- app/src/main/java/com/framgia/forder/screen/shopinfo/ShopInformationPageContainerViewModel.java
- app/src/main/java/com/framgia/forder/screen/shopmanagement/ItemShopManagementViewModel.java
- app/src/main/java/com/framgia/forder/screen/shopmanagement/ListShopManagementAdapter.java
- app/src/main/java/com/framgia/forder/screen/shopmanagement/ShopManagementFragment.java
- app/src/main/java/com/framgia/forder/screen/shopmanagement/ShopManagementViewModel.java
- app/src/main/res/layout/fragment_shop_infomation_page_container.xml
- app/src/main/res/layout/item_shop_management.xml
Feature UI Shop Update Information Page
Task : Shop Update Information
Effect: N/A
> [Sprint 5] Feature UI Shop Update Information Page

- app/src/main/java/com/framgia/forder/screen/shopinfo/ShopInformationPageAdapter.java
- app/src/main/java/com/framgia/forder/screen/shopinfo/ShopinfoContract.java
- app/src/main/java/com/framgia/forder/screen/shopinfo/ShopinfoFragment.java
- app/src/main/java/com/framgia/forder/screen/shopinfo/ShopinfoPresenter.java
- app/src/main/java/com/framgia/forder/screen/shopinfo/ShopinfoViewModel.java
- app/src/main/java/com/framgia/forder/screen/shopmanagement/ItemShopManagementViewModel.java
- app/src/main/res/drawable/ic_edits.xml
- app/src/main/res/drawable/ic_emails.xml
- app/src/main/res/drawable/ic_time.xml
- app/src/main/res/drawable/ic_user.xml
- app/src/main/res/layout/fragment_shopinfo.xml
- app/src/main/res/layout/item_user.xml
- app/src/main/res/values/strings.xml
Feature UI Shop Information
Task : Shop Update Information
Effect: N/A
> [Sprint 5] Feature UI Shop Information

- app/src/main/java/com/framgia/forder/data/model/CollectionAvatar.java
- app/src/main/java/com/framgia/forder/data/model/CollectionImage.java
- app/src/main/java/com/framgia/forder/data/model/Shop.java
- app/src/main/java/com/framgia/forder/data/model/ShopInfo.java
- app/src/main/java/com/framgia/forder/data/model/ShopManagement.java
- app/src/main/java/com/framgia/forder/screen/shopinfo/ShopInformationPageAdapter.java
- app/src/main/java/com/framgia/forder/screen/shopinfo/ShopInformationPageContainerFragment.java
- app/src/main/java/com/framgia/forder/screen/shopinfo/ShopinfoFragment.java
- app/src/main/java/com/framgia/forder/screen/shopinfo/ShopinfoViewModel.java
- app/src/main/java/com/framgia/forder/screen/shopmanagement/ItemShopManagementViewModel.java
- app/src/main/res/layout/fragment_shopinfo.xml
- app/src/main/res/values/strings.xml
Feature Logic Shop Information
Task : Shop Update Information
Effect: N/A
> [Sprint 5] Feature Logic Shop Information

- app/src/main/java/com/framgia/forder/screen/shopinfo/ShopInformationPageAdapter.java
- app/src/main/java/com/framgia/forder/screen/shopinfo/productshopinfo/ProductShopInfoContract.java
- app/src/main/java/com/framgia/forder/screen/shopinfo/productshopinfo/ProductShopInfoFragment.java
- app/src/main/java/com/framgia/forder/screen/shopinfo/productshopinfo/ProductShopInfoPresenter.java
- app/src/main/java/com/framgia/forder/screen/shopinfo/productshopinfo/ProductShopInfoViewModel.java
- app/src/main/res/layout/fragment_product_shop_info.xml
- app/src/main/res/layout/item_product_shop_info.xml
Feature UI Product In Shop Information
Task : Shop Update Information
Effect: N/A
> [Sprint 5] Feature UI Product In Shop Information

- app/src/main/java/com/framgia/forder/data/model/Shop.java
- app/src/main/java/com/framgia/forder/data/source/ShopDataSource.java
- app/src/main/java/com/framgia/forder/data/source/ShopRepository.java
- app/src/main/java/com/framgia/forder/data/source/remote/ShopRemoteDataSource.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/request/RegisterShopRequest.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/response/RegisterShopResponse.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/service/FOrderApi.java
- app/src/main/java/com/framgia/forder/screen/createshop/CreateshopFragment.java
- app/src/main/java/com/framgia/forder/screen/createshop/CreateshopViewModel.java
- app/src/main/java/com/framgia/forder/widgets/dialog/DialogManager.java
- app/src/main/res/layout/fragment_create_shop.xml
- app/src/main/res/values/strings.xml
Feature logic create shop
Link redmine : https://dev.framgia.com/redmine/issues/117506
Task : Create Shop
Effect: N/A
> [Sprint 6]Feature_logic_create_shop

- app/src/main/java/com/framgia/forder/data/source/remote/api/request/RegisterShopRequest.java
- app/src/main/java/com/framgia/forder/screen/createshop/CreateshopContract.java
- app/src/main/java/com/framgia/forder/screen/createshop/CreateshopFragment.java
- app/src/main/java/com/framgia/forder/screen/createshop/CreateshopPresenter.java
- app/src/main/java/com/framgia/forder/screen/createshop/CreateshopViewModel.java
- app/src/main/res/layout/fragment_create_shop.xml
- app/src/main/res/values/strings.xml
Feature logic create shop
Link redmine : https://dev.framgia.com/redmine/issues/117506
Task : Create Shop
Effect: N/A
> [Sprint 6]Feature_logic_create_shop_next

- app/src/main/java/com/framgia/forder/screen/managerdetail/ManagerDetailContract.java
- app/src/main/java/com/framgia/forder/screen/managerdetail/ManagerDetailFragment.java
- app/src/main/java/com/framgia/forder/screen/managerdetail/ManagerDetailPresenter.java
- app/src/main/java/com/framgia/forder/screen/managerdetail/ManagerDetailViewModel.java
- app/src/main/java/com/framgia/forder/screen/shopinfo/ItemManagerShopInfoViewModel.java
- app/src/main/java/com/framgia/forder/screen/shopinfo/ManagerShopInfoAdapter.java
- app/src/main/java/com/framgia/forder/screen/shopinfo/ShopinfoViewModel.java
- app/src/main/res/drawable/background_item.xml
- app/src/main/res/layout/fragment_managerdetail.xml
- app/src/main/res/layout/fragment_shopinfo.xml
- app/src/main/res/layout/item_manager.xml
- app/src/main/res/layout/item_shop_management.xml
- app/src/main/res/values/colors.xml
[Sprint 5] Feature UI Manager Details
Effect: N/A
> [Sprint 5] Feature UI Manager Details

- app/src/main/java/com/framgia/forder/data/model/RegisterShopInfo.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/request/RegisterShopRequest.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/response/RegisterShopResponse.java
- app/src/main/java/com/framgia/forder/screen/createshop/CreateshopContract.java
- app/src/main/java/com/framgia/forder/screen/createshop/CreateshopFragment.java
- app/src/main/java/com/framgia/forder/screen/createshop/CreateshopPresenter.java
- app/src/main/java/com/framgia/forder/screen/createshop/CreateshopViewModel.java
- app/src/main/java/com/framgia/forder/utils/binding/BindingUtils.java
- app/src/main/java/com/framgia/forder/utils/navigator/Navigator.java
- app/src/main/res/layout/fragment_create_shop.xml
- app/src/main/res/values/strings.xml
Feature logic create shop
Link redmine : https://dev.framgia.com/redmine/issues/117506
Task : Create Shop
Effect: N/A
> [Sprint 6]Feature_logic_create_shop_final

- app/src/main/java/com/framgia/forder/screen/managerdetail/ManagerDetailFragment.java
- app/src/main/java/com/framgia/forder/screen/managerdetail/ManagerDetailViewModel.java
- app/src/main/java/com/framgia/forder/screen/managerdetail/ManagerStatusCode.java
- app/src/main/res/layout/fragment_managerdetail.xml
- app/src/main/res/values/strings.xml
[Sprint 5] Feature Logic Manager Detail
Effect: N/A
> [Sprint 5] Feature Logic Manager Detail

- app/src/main/java/com/framgia/forder/data/model/Category.java
- app/src/main/java/com/framgia/forder/data/source/CategoryDataSource.java
- app/src/main/java/com/framgia/forder/data/source/CategoryRepository.java
- app/src/main/java/com/framgia/forder/data/source/ProductDataSource.java
- app/src/main/java/com/framgia/forder/data/source/ProductRepository.java
- app/src/main/java/com/framgia/forder/data/source/remote/CategoryRemoteDataSource.java
- app/src/main/java/com/framgia/forder/data/source/remote/ProductRemoteDataSource.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/request/RegisterProductRequest.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/response/CategoryResponse.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/service/FOrderApi.java
Feature logic create product
Effect: N/A
> [Sprint 7]Feature logic create product

- app/src/main/java/com/framgia/forder/data/model/Shop.java
- app/src/main/java/com/framgia/forder/data/source/ShopDataSource.java
- app/src/main/java/com/framgia/forder/data/source/ShopRepository.java
- app/src/main/java/com/framgia/forder/data/source/remote/ShopRemoteDataSource.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/request/UpdateShopRequest.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/service/FOrderApi.java
- app/src/main/java/com/framgia/forder/screen/shopupdate/ShopUpdateContract.java
- app/src/main/java/com/framgia/forder/screen/shopupdate/ShopUpdateFragment.java
- app/src/main/java/com/framgia/forder/screen/shopupdate/ShopUpdatePresenter.java
- app/src/main/java/com/framgia/forder/screen/shopupdate/ShopUpdateViewModel.java
- app/src/main/res/layout/fragment_shop_update.xml
- app/src/main/res/values/strings.xml
[Sprint 5] Feature Logic Update Shop
Effect: N/A
> [Sprint 5] Feature Logic Update Shop

- app/src/main/java/com/framgia/forder/data/model/Category.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/request/RegisterProductRequest.java
- app/src/main/java/com/framgia/forder/screen/createProduct/CreateProductContract.java
- app/src/main/java/com/framgia/forder/screen/createProduct/CreateProductFragment.java
- app/src/main/java/com/framgia/forder/screen/createProduct/CreateProductPresenter.java
- app/src/main/java/com/framgia/forder/screen/createProduct/CreateProductViewModel.java
- app/src/main/java/com/framgia/forder/screen/createshop/CreateshopContract.java
- app/src/main/java/com/framgia/forder/screen/createshop/CreateshopFragment.java
- app/src/main/java/com/framgia/forder/screen/createshop/CreateshopPresenter.java
- app/src/main/java/com/framgia/forder/screen/createshop/CreateshopViewModel.java
- app/src/main/java/com/framgia/forder/screen/shopinfo/productshopinfo/ProductShopInfoViewModel.java
- app/src/main/java/com/framgia/forder/utils/Constant.java
- app/src/main/java/com/framgia/forder/utils/Utils.java
- app/src/main/java/com/framgia/forder/utils/binding/BindingUtils.java
- app/src/main/res/layout/fragment_create_product.xml
- app/src/main/res/layout/fragment_create_shop.xml
- app/src/main/res/values-sw360dp/dimens.xml
- app/src/main/res/values/strings.xml
Feature logic create product next
Effect: N/A
> [Sprint 7]Feature logic create product next

- app/src/main/java/com/framgia/forder/data/model/RegisterProductInfo.java
- app/src/main/java/com/framgia/forder/data/source/ProductDataSource.java
- app/src/main/java/com/framgia/forder/data/source/ProductRepository.java
- app/src/main/java/com/framgia/forder/data/source/remote/ProductRemoteDataSource.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/request/UpdateProductRequest.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/response/UpdateProductResponse.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/service/FOrderApi.java
- app/src/main/java/com/framgia/forder/screen/createProduct/CreateProductViewModel.java
Feature logic update product
Effect: N/A
> [Sprint 7]Feature_logic_update_product

- app/src/main/java/com/framgia/forder/screen/updateProduct/UpdateProductContract.java
- app/src/main/java/com/framgia/forder/screen/updateProduct/UpdateProductFragment.java
- app/src/main/java/com/framgia/forder/screen/updateProduct/UpdateProductPresenter.java
- app/src/main/java/com/framgia/forder/screen/updateProduct/UpdateProductViewModel.java
- app/src/main/java/com/framgia/forder/utils/Constant.java
- app/src/main/res/layout/fragment_update_product.xml
- app/src/main/res/values/strings.xml
Feature logic update product next
Effect: N/A
> [Sprint 7]Feature_logic_update_product_next

- app/src/main/java/com/framgia/forder/data/model/CollectionAvatar.java
- app/src/main/java/com/framgia/forder/data/source/ShopDataSource.java
- app/src/main/java/com/framgia/forder/data/source/ShopRepository.java
- app/src/main/java/com/framgia/forder/data/source/remote/ShopRemoteDataSource.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/request/UpdateShopRequest.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/service/FOrderApi.java
- app/src/main/java/com/framgia/forder/screen/shopupdate/ShopUpdatePresenter.java
- app/src/main/java/com/framgia/forder/screen/shopupdate/ShopUpdateViewModel.java
[Sprint 5] Feature Send Data Update Shop
Effect: N/A
> [Sprint 5] Feature Send Data Update Shop

- app/src/main/java/com/framgia/forder/data/model/Order.java
- app/src/main/java/com/framgia/forder/data/model/OrderDetail.java
- app/src/main/java/com/framgia/forder/data/source/OrderDataSource.java
- app/src/main/java/com/framgia/forder/data/source/OrderRepository.java
- app/src/main/java/com/framgia/forder/data/source/remote/OrderRemoteDataSource.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/service/FOrderApi.java
- app/src/main/java/com/framgia/forder/screen/ordershop/OrderShopFragment.java
- app/src/main/java/com/framgia/forder/screen/shopinfo/ShopinfoViewModel.java
[Sprint 6] Feature Logic Get Data List Order Management Shop
Effect: N/A
> [Sprint 6] Feature Logic Get Data List Order Management Shop

- app/src/main/java/com/framgia/forder/data/source/remote/ShopRemoteDataSource.java
- app/src/main/java/com/framgia/forder/screen/shopDetail/ShopDetailContract.java
- app/src/main/java/com/framgia/forder/screen/shopDetail/ShopDetailFragment.java
- app/src/main/java/com/framgia/forder/screen/shopDetail/ShopDetailPresenter.java
- app/src/main/java/com/framgia/forder/screen/shopDetail/ShopDetailViewModel.java
- app/src/main/res/drawable/ic_description_note.xml
- app/src/main/res/layout/fragment_shop_detail.xml
[Sprint 3] Fix ui logic detail shop 
Task : Detail Shop 
Effect: N/A
> [Sprint3]Fix ui logic detail shop

- app/src/main/java/com/framgia/forder/data/model/Order.java
- app/src/main/java/com/framgia/forder/data/model/OrderDetail.java
- app/src/main/java/com/framgia/forder/screen/ordershop/ItemChildOrderViewModel.java
- app/src/main/java/com/framgia/forder/screen/ordershop/ItemGroupOrderViewModel.java
- app/src/main/java/com/framgia/forder/screen/ordershop/OrderShopAdapter.java
- app/src/main/java/com/framgia/forder/screen/ordershop/OrderShopContract.java
- app/src/main/java/com/framgia/forder/screen/ordershop/OrderShopFragment.java
- app/src/main/java/com/framgia/forder/screen/ordershop/OrderShopPresenter.java
- app/src/main/java/com/framgia/forder/screen/ordershop/OrderShopViewModel.java
- app/src/main/res/layout/fragment_ordershop.xml
[Sprint 6] Feature Logic Load Data List Order Management Shop
Effect: N/A
> [Sprint 6] Feature Logic Load Data List Order Management Shop

- app/src/main/java/com/framgia/forder/data/model/Product.java
- app/src/main/java/com/framgia/forder/data/model/RegisterProductInfo.java
- app/src/main/java/com/framgia/forder/screen/createProduct/CreateProductPresenter.java
- app/src/main/java/com/framgia/forder/screen/createProduct/CreateProductViewModel.java
- app/src/main/java/com/framgia/forder/screen/updateProduct/UpdateProductViewModel.java
- app/src/main/java/com/framgia/forder/utils/binding/BindingUtils.java
- app/src/main/res/layout/fragment_create_shop.xml
- app/src/main/res/layout/fragment_update_product.xml
[Sprint 8] Fix_logic_update_product
Effect: N/A
> [Sprint 8]Fix_logic_update_product

- app/src/main/java/com/framgia/forder/screen/shopinfo/productshopinfo/ItemProductShopInformationViewModel.java
- app/src/main/java/com/framgia/forder/screen/shopinfo/productshopinfo/ProductShopInfoViewModel.java
- app/src/main/java/com/framgia/forder/screen/shopinfo/productshopinfo/ProductShopInformationAdapter.java
- app/src/main/java/com/framgia/forder/screen/shopinfo/productshopinfo/UpdateProductListener.java
- app/src/main/res/layout/item_product_shop_info.xml
Feature detail product in shop management
Link redmine : https://dev.framgia.com/redmine/issues/114084
Task : Detail Product
Effect: N/A
> [Sprint 3]Feature detail product in shop management

- app/src/main/java/com/framgia/forder/data/model/Cart.java
- app/src/main/java/com/framgia/forder/data/model/CartItem.java
- app/src/main/java/com/framgia/forder/data/model/Product.java
- app/src/main/java/com/framgia/forder/data/model/ShoppingCart.java
- app/src/main/java/com/framgia/forder/data/source/local/ProductLocalDataSource.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/response/OrderCartResponse.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/service/FOrderApi.java
fix_logic_order_cart
Link redmine : https://dev.framgia.com/redmine/issues/114091
Task : Order
Effect: N/A
> [Sprint 3] Fix_logic_order_cart

- app/src/main/java/com/framgia/forder/data/source/ProductDataSource.java
- app/src/main/java/com/framgia/forder/data/source/ProductRepository.java
- app/src/main/java/com/framgia/forder/data/source/remote/ProductRemoteDataSource.java
- app/src/main/java/com/framgia/forder/screen/cart/ShoppingCartContract.java
- app/src/main/java/com/framgia/forder/screen/cart/ShoppingCartFragment.java
- app/src/main/java/com/framgia/forder/screen/cart/ShoppingCartPresenter.java
- app/src/main/java/com/framgia/forder/screen/cart/ShoppingCartViewModel.java
- app/src/main/res/values/strings.xml
Fix_logic_order_cart_next
Link redmine : https://dev.framgia.com/redmine/issues/114091
Task : Order
Effect: N/A
> [Sprint 3]Fix_logic_order_cart_next

- app/src/main/java/com/framgia/forder/data/model/Order.java
- app/src/main/java/com/framgia/forder/data/model/OrderDetail.java
- app/src/main/java/com/framgia/forder/screen/orderhistory/ItemHeaderOrderHistoryViewModel.java
- app/src/main/java/com/framgia/forder/screen/ordermanagement/checkorder/ItemParentCheckOrderViewModel.java
- app/src/main/java/com/framgia/forder/screen/ordershop/ItemChildOrderViewModel.java
- app/src/main/java/com/framgia/forder/screen/ordershop/ItemGroupOrderViewModel.java
- app/src/main/java/com/framgia/forder/screen/ordershop/OrderShopAdapter.java
- app/src/main/java/com/framgia/forder/utils/Constant.java
- app/src/main/res/drawable/button_orange.xml
- app/src/main/res/drawable/ic_accept.xml
- app/src/main/res/drawable/ic_reject.xml
- app/src/main/res/layout/fragment_ordershop.xml
- app/src/main/res/layout/item_product_order.xml
- app/src/main/res/layout/item_user_order.xml
- app/src/main/res/values/strings.xml
[Sprint 6] Feature Logic List Order Management Shop
Effect: N/A
> [Sprint 6] Feature Logic List Order Management Shop Final

- app/src/main/java/com/framgia/forder/data/model/OrderManagement.java
- app/src/main/java/com/framgia/forder/data/source/OrderDataSource.java
- app/src/main/java/com/framgia/forder/data/source/OrderRepository.java
- app/src/main/java/com/framgia/forder/data/source/remote/OrderRemoteDataSource.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/request/OrderManagerRequest.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/response/OrderManagerShopReponse.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/service/FOrderApi.java
[Sprint 6] Feature Logic Accept/ Reject In Order Management Shop (Model)
Effect: N/A
> [Sprint 6] Feature Logic Accept/ Reject In Order Management Shop (Model)

- app/src/main/java/com/framgia/forder/data/model/CartItem.java
- app/src/main/java/com/framgia/forder/data/source/ProductDataSource.java
- app/src/main/java/com/framgia/forder/data/source/ProductRepository.java
- app/src/main/java/com/framgia/forder/data/source/local/ProductLocalDataSource.java
- app/src/main/java/com/framgia/forder/screen/cart/notecart/NoteCartContract.java
- app/src/main/java/com/framgia/forder/screen/cart/notecart/NoteCartFragment.java
- app/src/main/java/com/framgia/forder/screen/cart/notecart/NoteCartPresenter.java
- app/src/main/java/com/framgia/forder/screen/cart/notecart/NoteCartViewModel.java
- app/src/main/res/layout/fragment_note_cart.xml
- app/src/main/res/values/strings.xml
Feature create note in cart
Link redmine : https://dev.framgia.com/redmine/issues/114091
Task : Order
Effect: N/A
> [Sprint 3]Feature create note in cart

- app/src/main/java/com/framgia/forder/screen/ordershop/ItemChildOrderViewModel.java
- app/src/main/java/com/framgia/forder/screen/ordershop/ItemGroupOrderViewModel.java
- app/src/main/java/com/framgia/forder/screen/ordershop/OrderShopAdapter.java
- app/src/main/java/com/framgia/forder/screen/ordershop/OrderShopContract.java
- app/src/main/java/com/framgia/forder/screen/ordershop/OrderShopFragment.java
- app/src/main/java/com/framgia/forder/screen/ordershop/OrderShopPresenter.java
- app/src/main/java/com/framgia/forder/screen/ordershop/OrderShopViewModel.java
- app/src/main/res/drawable/ic_list_order.xml
- app/src/main/res/layout/fragment_ordershop.xml
- app/src/main/res/layout/item_user_order.xml
- app/src/main/res/values/strings.xml
[Sprint 6] Feature Logic Accept/Reject Order Management Shop Final
Effect: N/A
> [Sprint 6] Feature Logic Accept/Reject Order Management Shop Final

- app/src/main/java/com/framgia/forder/data/model/Cart.java
- app/src/main/java/com/framgia/forder/screen/cart/ItemShoppingCartViewModel.java
- app/src/main/java/com/framgia/forder/screen/cart/OrderItemListener.java
- app/src/main/java/com/framgia/forder/screen/cart/ShoppingCartContract.java
- app/src/main/java/com/framgia/forder/screen/cart/ShoppingCartPresenter.java
- app/src/main/java/com/framgia/forder/screen/cart/ShoppingCartViewModel.java
- app/src/main/java/com/framgia/forder/screen/cart/notecart/NoteCartViewModel.java
- app/src/main/java/com/framgia/forder/utils/Utils.java
- app/src/main/java/com/framgia/forder/utils/navigator/Navigator.java
- app/src/main/res/drawable/ic_notes.xml
- app/src/main/res/layout/item_content_cart.xml
- app/src/main/res/values-sw360dp/dimens.xml
Feature create note in cart next
Link redmine : https://dev.framgia.com/redmine/issues/114091
Task : Order
Effect: N/A
> [Sprint 3]Feature_create_note_in_cart_next

- app/src/main/java/com/framgia/forder/data/source/OrderDataSource.java
- app/src/main/java/com/framgia/forder/data/source/OrderRepository.java
- app/src/main/java/com/framgia/forder/data/source/remote/OrderRemoteDataSource.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/response/CloseOrderResponse.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/service/FOrderApi.java
- app/src/main/java/com/framgia/forder/screen/ordershop/OrderShopContract.java
- app/src/main/java/com/framgia/forder/screen/ordershop/OrderShopPresenter.java
- app/src/main/java/com/framgia/forder/screen/ordershop/OrderShopViewModel.java
- app/src/main/res/layout/fragment_ordershop.xml
- app/src/main/res/values/strings.xml
[Sprint 6] Feature Logic Close Order
Task : Order Management
Effect: N/A
> [Sprint 6] Feature Logic Close Order

- app/src/main/java/com/framgia/forder/data/source/DomainDataSource.java
- app/src/main/java/com/framgia/forder/data/source/DomainRepository.java
- app/src/main/java/com/framgia/forder/data/source/remote/DomainRemoteDataSource.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/response/DomainManagementResponse.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/service/FOrderApi.java
- app/src/main/java/com/framgia/forder/screen/domainmanagement/ItemDomainManagementViewModel.java
- app/src/main/java/com/framgia/forder/utils/Constant.java
- app/src/main/java/com/framgia/forder/utils/binding/BindingUtils.java
- app/src/main/res/drawable/ic_public.xml
- app/src/main/res/layout/item_domain_management.xml
Feature create logic domain management
Effect: N/A
> [Sprint 6]Feature create logic domain management

- app/src/main/java/com/framgia/forder/screen/domainmanagement/DomainManagementAdapter.java
- app/src/main/java/com/framgia/forder/screen/domainmanagement/DomainManagementContract.java
- app/src/main/java/com/framgia/forder/screen/domainmanagement/DomainManagementFragment.java
- app/src/main/java/com/framgia/forder/screen/domainmanagement/DomainManagementPresenter.java
- app/src/main/java/com/framgia/forder/screen/domainmanagement/DomainManagementViewModel.java
- app/src/main/res/layout/fragment_domain_management.xml
- app/src/main/res/layout/item_domain_management.xml
Feature create logic domain management next
Effect: N/A
> [Sprint 6]Feature create logic domain management next

- app/src/main/java/com/framgia/forder/screen/orderhistoryshop/OrderHistoryPageAdapter.java
- app/src/main/java/com/framgia/forder/screen/orderhistoryshop/OrderHistoryShopContract.java
- app/src/main/java/com/framgia/forder/screen/orderhistoryshop/OrderHistoryShopFragment.java
- app/src/main/java/com/framgia/forder/screen/orderhistoryshop/OrderHistoryShopPresenter.java
- app/src/main/java/com/framgia/forder/screen/orderhistoryshop/OrderHistoryShopViewModel.java
- app/src/main/java/com/framgia/forder/screen/shopinfo/ShopinfoViewModel.java
- app/src/main/res/layout/fragment_order_history_shop.xml
- app/src/main/res/layout/fragment_shopinfo.xml
- app/src/main/res/values/strings.xml
[Sprint 6] Feature Create Page Container Order History
Effect: N/A
> [Sprint 6] Feature Create Page Container Order History

- app/src/main/java/com/framgia/forder/data/model/OrderHistory.java
- app/src/main/java/com/framgia/forder/data/model/OrderHistoryList.java
- app/src/main/java/com/framgia/forder/screen/orderhistoryshop/OrderHistoryPageAdapter.java
- app/src/main/java/com/framgia/forder/screen/orderhistoryshop/listdoneorders/ListDoneOrderAdapter.java
- app/src/main/java/com/framgia/forder/screen/orderhistoryshop/listdoneorders/ListDoneOrdersContract.java
- app/src/main/java/com/framgia/forder/screen/orderhistoryshop/listdoneorders/ListDoneOrdersFragment.java
- app/src/main/java/com/framgia/forder/screen/orderhistoryshop/listdoneorders/ListDoneOrdersPresenter.java
- app/src/main/java/com/framgia/forder/screen/orderhistoryshop/listdoneorders/ListDoneOrdersViewModel.java
- app/src/main/res/layout/fragment_list_done_orders.xml
- app/src/main/res/layout/item_done_orders.xml
[Print 6] Feature UI List Done Orders
Effect: N/A
> [Sprint 6] Feature UI List Done Orders

- app/src/main/java/com/framgia/forder/screen/domainmanagement/DomainManagementFragment.java
- app/src/main/java/com/framgia/forder/screen/domainmanagement/DomainManagementViewModel.java
- app/src/main/java/com/framgia/forder/screen/domainmanagement/adddomain/AddDomainContract.java
- app/src/main/java/com/framgia/forder/screen/domainmanagement/adddomain/AddDomainFragment.java
- app/src/main/java/com/framgia/forder/screen/domainmanagement/adddomain/AddDomainListener.java
- app/src/main/java/com/framgia/forder/screen/domainmanagement/adddomain/AddDomainPresenter.java
- app/src/main/java/com/framgia/forder/screen/domainmanagement/adddomain/AddDomainViewModel.java
- app/src/main/java/com/framgia/forder/utils/navigator/Navigator.java
- app/src/main/res/layout/fragment_add_domain.xml
- app/src/main/res/values/strings.xml
Feature create ui add domain
Effect: N/A
> [Sprint 6]Feature create ui add domain

- app/src/main/java/com/framgia/forder/data/model/RegisterDomain.java
- app/src/main/java/com/framgia/forder/data/source/DomainDataSource.java
- app/src/main/java/com/framgia/forder/data/source/DomainRepository.java
- app/src/main/java/com/framgia/forder/data/source/remote/DomainRemoteDataSource.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/request/RegisterDomainRequest.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/response/RegisterDomainResponse.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/service/FOrderApi.java
Feature create logic add domain
Effect: N/A
> [Sprint 6]Feature_create_logic_add_domain

- app/src/main/java/com/framgia/forder/data/model/OrderHistoryList.java
- app/src/main/java/com/framgia/forder/data/source/OrderDataSource.java
- app/src/main/java/com/framgia/forder/data/source/OrderRepository.java
- app/src/main/java/com/framgia/forder/data/source/remote/OrderRemoteDataSource.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/response/OrderHistoryShopResponse.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/service/FOrderApi.java
- app/src/main/java/com/framgia/forder/screen/orderhistoryshop/OrderHistoryPageAdapter.java
- app/src/main/java/com/framgia/forder/screen/orderhistoryshop/OrderHistoryShopFragment.java
- app/src/main/java/com/framgia/forder/screen/orderhistoryshop/listdoneorders/ListDoneOrdersFragment.java
- app/src/main/java/com/framgia/forder/screen/shopinfo/ShopinfoViewModel.java
[Sprint 6] Feature Get List Order History
Effect: N/A
> [Sprint 6] Feature Get List Order History

- app/src/main/java/com/framgia/forder/data/source/OrderDataSource.java
- app/src/main/java/com/framgia/forder/data/source/OrderRepository.java
- app/src/main/java/com/framgia/forder/data/source/remote/OrderRemoteDataSource.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/response/OrderHistoryShopResponse.java
- app/src/main/java/com/framgia/forder/screen/orderhistoryshop/listdoneorders/ListDoneOrderAdapter.java
- app/src/main/java/com/framgia/forder/screen/orderhistoryshop/listdoneorders/ListDoneOrdersContract.java
- app/src/main/java/com/framgia/forder/screen/orderhistoryshop/listdoneorders/ListDoneOrdersFragment.java
- app/src/main/java/com/framgia/forder/screen/orderhistoryshop/listdoneorders/ListDoneOrdersPresenter.java
- app/src/main/java/com/framgia/forder/screen/orderhistoryshop/listdoneorders/ListDoneOrdersViewModel.java
- app/src/main/res/layout/fragment_list_done_orders.xml
[Sprint 6] Freature Load List Done Orders Shop
Effect: N/A
> [Sprint 6] Freature Load List Done Orders Shop

- app/src/main/java/com/framgia/forder/screen/domainmanagement/DomainManagementContract.java
- app/src/main/java/com/framgia/forder/screen/domainmanagement/DomainManagementPresenter.java
- app/src/main/java/com/framgia/forder/screen/domainmanagement/DomainManagementViewModel.java
- app/src/main/java/com/framgia/forder/screen/domainmanagement/adddomain/AddDomainContract.java
- app/src/main/java/com/framgia/forder/screen/domainmanagement/adddomain/AddDomainFragment.java
- app/src/main/java/com/framgia/forder/screen/domainmanagement/adddomain/AddDomainListener.java
- app/src/main/java/com/framgia/forder/screen/domainmanagement/adddomain/AddDomainViewModel.java
- app/src/main/res/values/strings.xml
Feature create logic add domain next
Effect: N/A
> [Sprint 6]Feature create logic add domain next

- app/src/main/java/com/framgia/forder/screen/orderhistoryshop/OrderHistoryPageAdapter.java
- app/src/main/java/com/framgia/forder/screen/orderhistoryshop/listrejectorders/ListRejectOrdersAdapter.java
- app/src/main/java/com/framgia/forder/screen/orderhistoryshop/listrejectorders/ListRejectOrdersContract.java
- app/src/main/java/com/framgia/forder/screen/orderhistoryshop/listrejectorders/ListRejectOrdersFragment.java
- app/src/main/java/com/framgia/forder/screen/orderhistoryshop/listrejectorders/ListRejectOrdersPresenter.java
- app/src/main/java/com/framgia/forder/screen/orderhistoryshop/listrejectorders/ListRejectOrdersViewModel.java
- app/src/main/res/drawable/border_number.xml
- app/src/main/res/layout/fragment_list_reject_orders.xml
- app/src/main/res/layout/item_reject_orders.xml
[Sprint 6] Feature Logic List Reject Orders Shop
Effect: N/A
> [Sprint 6] Feature Logic List Reject Orders Shop

- app/src/main/java/com/framgia/forder/data/model/Order.java
- app/src/main/java/com/framgia/forder/data/model/OrderDetail.java
- app/src/main/java/com/framgia/forder/data/source/OrderDataSource.java
- app/src/main/java/com/framgia/forder/data/source/remote/OrderRemoteDataSource.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/service/FOrderApi.java
- app/src/main/java/com/framgia/forder/screen/orderhistory/ItemHeaderOrderHistoryViewModel.java
- app/src/main/java/com/framgia/forder/screen/orderhistory/ItemOrderHistoryViewModel.java
- app/src/main/java/com/framgia/forder/screen/ordershop/ItemGroupOrderViewModel.java
- app/src/main/res/layout/item_header_order_history.xml
- app/src/main/res/layout/item_order_history.xml
Fix logic order history
Link redmine : https://dev.framgia.com/redmine/issues/114363
Task : List order history
Effect: N/A
> [Sprint 3]Fix logic order history

- app/src/main/java/com/framgia/forder/data/source/OrderRepository.java
- app/src/main/java/com/framgia/forder/screen/orderhistory/OrderHistoryContract.java
- app/src/main/java/com/framgia/forder/screen/orderhistory/OrderHistoryFragment.java
- app/src/main/java/com/framgia/forder/screen/orderhistory/OrderHistoryPresenter.java
- app/src/main/java/com/framgia/forder/screen/orderhistory/OrderHistoryViewModel.java
- app/src/main/java/com/framgia/forder/utils/Constant.java
- app/src/main/java/com/framgia/forder/utils/Utils.java
- app/src/main/res/layout/item_order_history.xml
- app/src/main/res/values/strings.xml
Fix logic order history next
Link redmine : https://dev.framgia.com/redmine/issues/114363
Task : List order history
Effect: N/A
> [Sprint 3]Fix logic order history next

- app/src/main/java/com/framgia/forder/screen/domainmanagement/DomainManagementListener.java
- app/src/main/java/com/framgia/forder/screen/domainmanagement/DomainManagementViewModel.java
- app/src/main/java/com/framgia/forder/screen/domainmanagement/ItemDomainManagementViewModel.java
- app/src/main/res/drawable/ic_exit.xml
- app/src/main/res/layout/item_domain_management.xml
Fix UI Domain Management 
Effect: N/A
> [Sprint 6]Fix UI Domain Management

- app/src/main/java/com/framgia/forder/data/source/DomainDataSource.java
- app/src/main/java/com/framgia/forder/data/source/DomainRepository.java
- app/src/main/java/com/framgia/forder/data/source/remote/DomainRemoteDataSource.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/response/DeleteDomainResponse.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/response/DeleteUserInDomainResponse.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/service/FOrderApi.java
- app/src/main/java/com/framgia/forder/screen/domainmanagement/DomainManagementListener.java
- app/src/main/java/com/framgia/forder/screen/domainmanagement/DomainManagementViewModel.java
- app/src/main/java/com/framgia/forder/screen/domainmanagement/ItemDomainManagementViewModel.java
Feature delete and leave domain 
Effect: N/A
> [Sprint 6]Feature delete and leave domain

- app/src/main/java/com/framgia/forder/screen/domainmanagement/DomainManagementContract.java
- app/src/main/java/com/framgia/forder/screen/domainmanagement/DomainManagementFragment.java
- app/src/main/java/com/framgia/forder/screen/domainmanagement/DomainManagementPresenter.java
- app/src/main/java/com/framgia/forder/screen/domainmanagement/DomainManagementViewModel.java
- app/src/main/res/values/strings.xml
Feature delete and leave domain_next
Effect: N/A
> [Sprint 6]Feature Delete And Leave Domain Next

- app/src/main/java/com/framgia/forder/data/model/DomainManagement.java
- app/src/main/java/com/framgia/forder/screen/domainmanagement/DomainManagementListener.java
- app/src/main/java/com/framgia/forder/screen/domainmanagement/DomainManagementViewModel.java
- app/src/main/java/com/framgia/forder/screen/domainmanagement/ItemDomainManagementViewModel.java
- app/src/main/java/com/framgia/forder/screen/domainmanagement/editdomain/EditDomainListener.java
- app/src/main/java/com/framgia/forder/screen/domainmanagement/editdomain/EditdomainContract.java
- app/src/main/java/com/framgia/forder/screen/domainmanagement/editdomain/EditdomainFragment.java
- app/src/main/java/com/framgia/forder/screen/domainmanagement/editdomain/EditdomainPresenter.java
- app/src/main/java/com/framgia/forder/screen/domainmanagement/editdomain/EditdomainViewModel.java
- app/src/main/res/layout/fragment_edit_domain.xml
Feature Create UI Edit Domain
Effect: N/A
> [Sprint 6]Feature Create UI Edit Domain

- app/src/main/java/com/framgia/forder/data/source/DomainDataSource.java
- app/src/main/java/com/framgia/forder/data/source/DomainRepository.java
- app/src/main/java/com/framgia/forder/data/source/remote/DomainRemoteDataSource.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/response/EditDomainResponse.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/service/FOrderApi.java
- app/src/main/java/com/framgia/forder/screen/domainmanagement/editdomain/EditdomainFragment.java
- app/src/main/res/values/strings.xml
Feature logic edit domain
Effect: N/A
> [Sprint 6]Feature logic edit domain

- app/src/main/java/com/framgia/forder/screen/domainmanagement/DomainManagementContract.java
- app/src/main/java/com/framgia/forder/screen/domainmanagement/DomainManagementFragment.java
- app/src/main/java/com/framgia/forder/screen/domainmanagement/DomainManagementPresenter.java
- app/src/main/java/com/framgia/forder/screen/domainmanagement/DomainManagementViewModel.java
- app/src/main/java/com/framgia/forder/screen/domainmanagement/editdomain/EditDomainListener.java
- app/src/main/java/com/framgia/forder/screen/domainmanagement/editdomain/EditdomainViewModel.java
- app/src/main/java/com/framgia/forder/utils/navigator/Navigator.java
Feature logic edit domain next
Effect: N/A
> [Sprint 6]Feature logic edit domain next

- app/src/main/java/com/framgia/forder/data/model/DomainManagement.java
- app/src/main/java/com/framgia/forder/data/model/Order.java
- app/src/main/java/com/framgia/forder/data/model/OrderDetail.java
- app/src/main/java/com/framgia/forder/screen/domainmanagement/DomainManagementContract.java
- app/src/main/java/com/framgia/forder/screen/domainmanagement/DomainManagementPresenter.java
- app/src/main/java/com/framgia/forder/screen/domainmanagement/DomainManagementViewModel.java
- app/src/main/java/com/framgia/forder/screen/domainmanagement/ItemDomainManagementViewModel.java
- app/src/main/java/com/framgia/forder/screen/domainmanagement/editdomain/EditdomainFragment.java
- app/src/main/res/layout/item_domain_management.xml
Fix ui domain management with rule and status color in order history
Effect: N/A
> [Sprint 6]Fix ui domain management next

- app/src/main/java/com/framgia/forder/data/source/remote/SearchRemoteDataSource.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/response/SearchResponse.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/service/FOrderApi.java
- app/src/main/java/com/framgia/forder/screen/mainpage/product/ItemProductViewModel.java
- app/src/main/java/com/framgia/forder/screen/searchpage/SearchContainerContract.java
- app/src/main/java/com/framgia/forder/screen/searchpage/SearchContainerFragment.java
- app/src/main/java/com/framgia/forder/screen/searchpage/SearchContainerPresenter.java
- app/src/main/java/com/framgia/forder/screen/searchpage/SearchContainerViewModel.java
- app/src/main/res/layout/fragment_search_container.xml
Fix Logic Search 
Link redmine : https://dev.framgia.com/redmine/issues/113283
Task : Feature Search Screen
Effect: N/A
> Fix Logic Search

- app/src/main/java/com/framgia/forder/data/model/Product.java
- app/src/main/java/com/framgia/forder/screen/mainpage/MainPageViewModel.java
- app/src/main/java/com/framgia/forder/screen/mainpage/product/ItemProductViewModel.java
- app/src/main/res/layout/item_product.xml
- app/src/main/res/values/strings.xml
[Sprint Maintain] Fix List Product In Main
Link redmine :https://dev.framgia.com/redmine/issues/122832
Effect : N/A
> [Sprint Maintain] Fix List Product In Main

- app/src/main/java/com/framgia/forder/data/source/remote/SearchRemoteDataSource.java
- app/src/main/java/com/framgia/forder/screen/mainpage/shop/ItemShopViewModel.java
- app/src/main/java/com/framgia/forder/screen/productdetail/ProductDetailViewModel.java
- app/src/main/java/com/framgia/forder/screen/searchproduct/ProductSearchResultContract.java
- app/src/main/java/com/framgia/forder/screen/searchproduct/ProductSearchResultFragment.java
- app/src/main/java/com/framgia/forder/screen/searchproduct/ProductSearchResultPresenter.java
- app/src/main/java/com/framgia/forder/screen/searchproduct/ProductSearchResultViewModel.java
Fix Logic Search next
Link redmine : https://dev.framgia.com/redmine/issues/113283
Task : Feature Search Screen
Effect: N/A
> [Sprint 2]Fix Logic Search Next

- app/src/main/java/com/framgia/forder/data/model/CartItem.java
- app/src/main/java/com/framgia/forder/screen/listProduct/ListProductContract.java
- app/src/main/java/com/framgia/forder/screen/listProduct/ListProductFragment.java
- app/src/main/java/com/framgia/forder/screen/listProduct/ListProductPresenter.java
- app/src/main/java/com/framgia/forder/screen/listProduct/ListProductViewModel.java
- app/src/main/java/com/framgia/forder/screen/mainpage/MainPageViewModel.java
- app/src/main/java/com/framgia/forder/screen/mainpage/product/ItemProductViewModel.java
- app/src/main/java/com/framgia/forder/screen/mainpage/product/OrderListener.java
- app/src/main/java/com/framgia/forder/screen/quickorder/QuickOrderListener.java
- app/src/main/java/com/framgia/forder/screen/searchproduct/ProductSearchResultViewModel.java
Feature logic quick order
Link redmine : https://dev.framgia.com/redmine/issues/123089
Task : Quick Order
Effect: N/A
> [Sprint Maintain]Feature logic quick order

- app/src/main/java/com/framgia/forder/screen/listProduct/ListProductViewModel.java
- app/src/main/java/com/framgia/forder/screen/quickorder/DismissDialogListener.java
- app/src/main/java/com/framgia/forder/screen/quickorder/QuickOrderFragment.java
- app/src/main/java/com/framgia/forder/screen/quickorder/QuickOrderViewModel.java
- app/src/main/java/com/framgia/forder/utils/navigator/Navigator.java
- app/src/main/res/layout/fragment_quick_order.xml
- app/src/main/res/values/strings.xml
Feature Logic Quick Order Next
Link redmine : https://dev.framgia.com/redmine/issues/123089
Task : Quick Order
Effect: N/A
> [Sprint Maintain]Feature Logic Quick Order Next

- app/src/main/java/com/framgia/forder/data/source/ShopDataSource.java
- app/src/main/java/com/framgia/forder/data/source/ShopRepository.java
- app/src/main/java/com/framgia/forder/data/source/remote/ShopRemoteDataSource.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/response/DeleteShopInDomainResponse.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/response/ShopInDomainResponse.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/service/FOrderApi.java
- app/src/main/java/com/framgia/forder/screen/domainmanagement/DomainManagementListener.java
- app/src/main/java/com/framgia/forder/screen/domainmanagement/DomainManagementViewModel.java
- app/src/main/java/com/framgia/forder/screen/domainmanagement/ItemDomainManagementViewModel.java
Feature logic shop in domain
Effect: N/A
> [Sprint 6]Feature logic shop in domain

- app/build.gradle
- app/google-services.json
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/framgia/forder/data/source/local/MyFirebaseInstanceIDService.java
- app/src/main/java/com/framgia/forder/data/source/local/MyFirebaseMessagingService.java
- build.gradle
- dependencies.gradle
[Sprint 8 ]Feature Notification Device
Link redmine :https://dev.framgia.com/redmine/issues/123390
Task: Handle receive notification	
Effect : N/A
> [Sprint 8 ]Feature Notification Device

- app/src/main/java/com/framgia/forder/data/model/ShopInDomain.java
- app/src/main/java/com/framgia/forder/screen/shopindomain/ItemShopInDomainViewModel.java
- app/src/main/java/com/framgia/forder/screen/shopindomain/ShopInDomainAdapter.java
- app/src/main/java/com/framgia/forder/screen/shopindomain/ShopInDomainContract.java
- app/src/main/java/com/framgia/forder/screen/shopindomain/ShopInDomainFragment.java
- app/src/main/java/com/framgia/forder/screen/shopindomain/ShopInDomainListener.java
- app/src/main/java/com/framgia/forder/screen/shopindomain/ShopInDomainPresenter.java
- app/src/main/java/com/framgia/forder/screen/shopindomain/ShopInDomainViewModel.java
- app/src/main/res/layout/fragment_shop_in_domain.xml
- app/src/main/res/layout/item_shop_in_domain.xml
Feature logic shop in domain next
Effect: N/A
> [Sprint 6]Feature logic shop in domain next

- app/src/main/java/com/framgia/forder/screen/mainpage/MainPageFragment.java
- app/src/main/java/com/framgia/forder/screen/mainpage/MainPageViewModel.java
- app/src/main/java/com/framgia/forder/screen/mainpage/shop/ShopPageAdapter.java
- app/src/main/java/com/framgia/forder/screen/mainpage/shop/ShopPageContract.java
- app/src/main/java/com/framgia/forder/screen/mainpage/shop/ShopPageFragment.java
- app/src/main/java/com/framgia/forder/screen/mainpage/shop/ShopPagePresenter.java
- app/src/main/java/com/framgia/forder/screen/mainpage/shop/ShopPageViewModel.java
- app/src/main/res/layout/fragment_custom_slide_show.xml
- app/src/main/res/layout/fragment_main_page.xml
[Sprint Maintain] Fix UI List Top Shop Main 2
Link redmine: "https://dev.framgia.com/redmine/issues/123344"
Task : Update main page
Effect: N/A
> [Sprint Maintain] Fix UI List Top Shop Main 2

- app/src/main/java/com/framgia/forder/data/source/ProductRepository.java
- app/src/main/java/com/framgia/forder/screen/cart/ShoppingCartFragment.java
- app/src/main/java/com/framgia/forder/screen/cart/notecart/NoteCartFragment.java
- app/src/main/java/com/framgia/forder/screen/listProduct/ListProductFragment.java
- app/src/main/java/com/framgia/forder/screen/mainpage/MainPageFragment.java
- app/src/main/java/com/framgia/forder/screen/productdetail/ProductDetailFragment.java
[Sprint Maintain] Fix Logic Quick Oder
https://dev.framgia.com/redmine/issues/123733
Task : Fix Logic Quick Oder
Effect: N/A
> Fix Logic Quick Oder

- app/src/main/java/com/framgia/forder/screen/shopinfo/ShopinfoViewModel.java
- app/src/main/res/drawable/ic_edits.xml
- app/src/main/res/drawable/ic_stars.xml
- app/src/main/res/layout/fragment_shopinfo.xml
- app/src/main/res/layout/fragment_shoppingcart.xml
- app/src/main/res/values/strings.xml
[Sprint Maintain]Fix shop management detail
Link redmine :https://dev.framgia.com/redmine/issues/123881
Task: Fix Shop Management Info
Effect : N/A
> [Sprint Maintain]Fix shop management detail

- app/src/main/java/com/framgia/forder/data/model/OwnerShop.java
- app/src/main/java/com/framgia/forder/screen/managerinshop/ItemManagerInShopViewModel.java
- app/src/main/java/com/framgia/forder/screen/managerinshop/ManagerInShopContract.java
- app/src/main/java/com/framgia/forder/screen/managerinshop/ManagerInShopFragment.java
- app/src/main/java/com/framgia/forder/screen/managerinshop/ManagerInShopPresenter.java
- app/src/main/java/com/framgia/forder/screen/managerinshop/ManagerInShopViewModel.java
- app/src/main/java/com/framgia/forder/utils/navigator/Navigator.java
- app/src/main/res/layout/fragment_manager_in_shop.xml
- app/src/main/res/layout/item_manager_in_shop.xml
- app/src/main/res/values/strings.xml
Feature ui manager in shop
Effect: N/A
> [Sprint 6]Feature ui manager in shop

- app/src/main/java/com/framgia/forder/data/source/DomainDataSource.java
- app/src/main/java/com/framgia/forder/data/source/DomainRepository.java
- app/src/main/java/com/framgia/forder/data/source/remote/DomainRemoteDataSource.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/response/ChangeRuleOfUserResponse.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/response/UserInDomainResponse.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/service/FOrderApi.java
- app/src/main/java/com/framgia/forder/utils/binding/BindingUtils.java
- app/src/main/res/drawable-xxhdpi/ic_three_dots.xml
- app/src/main/res/layout/item_user_in_domain.xml
Feature logic user in domain
Effect: N/A
> [Sprint 6]Feature logic user in domain

- app/src/main/java/com/framgia/forder/screen/domainmanagement/DomainManagementViewModel.java
- app/src/main/java/com/framgia/forder/screen/userindomain/ItemUserInDomainViewModel.java
- app/src/main/java/com/framgia/forder/screen/userindomain/UserInDomainAdapter.java
- app/src/main/java/com/framgia/forder/screen/userindomain/UserInDomainContract.java
- app/src/main/java/com/framgia/forder/screen/userindomain/UserInDomainFragment.java
- app/src/main/java/com/framgia/forder/screen/userindomain/UserInDomainPresenter.java
- app/src/main/java/com/framgia/forder/screen/userindomain/UserInDomainViewModel.java
- app/src/main/res/layout/fragment_user_in_domain.xml
- app/src/main/res/layout/item_user_in_domain.xml
- app/src/main/res/values/strings.xml
Feature logic user in domain next
Effect: N/A
> [Sprint 6]Feature logic user in domain next

- app/src/main/java/com/framgia/forder/screen/searchpage/SearchContainerFragment.java
- app/src/main/java/com/framgia/forder/screen/searchpage/SearchContainerViewModel.java
- app/src/main/java/com/framgia/forder/screen/searchproduct/ProductSearchResultContract.java
- app/src/main/java/com/framgia/forder/screen/searchproduct/ProductSearchResultFragment.java
- app/src/main/java/com/framgia/forder/screen/searchproduct/ProductSearchResultPresenter.java
- app/src/main/java/com/framgia/forder/screen/searchproduct/ProductSearchResultViewModel.java
- app/src/main/java/com/framgia/forder/screen/shopDetail/ShopDetailViewModel.java
- app/src/main/java/com/framgia/forder/utils/binding/BindingUtils.java
- app/src/main/res/layout/fragment_search_container.xml
Fix bug search and add quickorder in product
Link redmine : https://dev.framgia.com/redmine/issues/125149
Effect: N/A
> [Sprint Maintain] Fix bug search and add quick order in product

- app/src/main/java/com/framgia/forder/data/model/Comment.java
- app/src/main/java/com/framgia/forder/data/model/RegisterSendComment.java
- app/src/main/java/com/framgia/forder/data/source/ProductDataSource.java
- app/src/main/java/com/framgia/forder/data/source/ProductRepository.java
- app/src/main/java/com/framgia/forder/data/source/remote/ProductRemoteDataSource.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/request/CommentRequest.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/response/BaseResponse.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/response/CommentResponse.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/service/FOrderApi.java
- app/src/main/java/com/framgia/forder/screen/productdetail/ProductDetailContract.java
- app/src/main/java/com/framgia/forder/screen/productdetail/ProductDetailFragment.java
- app/src/main/java/com/framgia/forder/screen/productdetail/ProductDetailPresenter.java
- app/src/main/java/com/framgia/forder/screen/productdetail/ProductDetailViewModel.java
- app/src/main/java/com/framgia/forder/screen/productdetail/adapter/ItemUserViewModel.java
[Sprint Maintain] Fix Logic List Comment & Send Comment
Link redmine : https://dev.framgia.com/redmine/issues/125130
Effect: N/A
> [Sprint Maintain] Fix Logic List Comment & Send Comment

- app/src/main/java/com/framgia/forder/data/model/Shop.java
- app/src/main/java/com/framgia/forder/data/source/remote/ShopRemoteDataSource.java
- app/src/main/java/com/framgia/forder/screen/shopDetail/ShopDetailContract.java
- app/src/main/java/com/framgia/forder/screen/shopDetail/ShopDetailFragment.java
- app/src/main/java/com/framgia/forder/screen/shopDetail/ShopDetailPresenter.java
- app/src/main/java/com/framgia/forder/screen/shopDetail/ShopDetailViewModel.java
- app/src/main/java/com/framgia/forder/utils/binding/BindingUtils.java
- app/src/main/res/layout/fragment_shop_detail.xml
[Sprint Maintain] Feature Fix UI Detail Shop
Link redmine : https://dev.framgia.com/redmine/issues/125385
Effect: N/A
> [Sprint Maintain]Feature Fix UI Detail Shop

- app/src/main/java/com/framgia/forder/screen/chooseDomain/ChooseDomainActivity.java
- app/src/main/java/com/framgia/forder/screen/chooseDomain/ChooseDomainPresenter.java
- app/src/main/java/com/framgia/forder/screen/chooseDomain/ChooseDomainViewModel.java
- app/src/main/java/com/framgia/forder/screen/login/LoginActivity.java
- app/src/main/java/com/framgia/forder/screen/login/LoginContract.java
- app/src/main/java/com/framgia/forder/screen/login/LoginPresenter.java
- app/src/main/java/com/framgia/forder/screen/login/LoginViewModel.java
- app/src/main/res/layout/activity_choose_domain.xml
- app/src/main/res/layout/activity_login.xml
- app/src/main/res/values/strings.xml
[Sprint Maintain] Add Progress Bar Login & Choose Domain
Link redmine : https://dev.framgia.com/redmine/issues/126102
Effect: N/A
> [Sprint Maintain] Add Progress Bar Login & Choose Domain

- app/src/main/java/com/framgia/forder/screen/listProduct/ListProductContract.java
- app/src/main/java/com/framgia/forder/screen/listProduct/ListProductFragment.java
- app/src/main/java/com/framgia/forder/screen/listProduct/ListProductPresenter.java
- app/src/main/java/com/framgia/forder/screen/listProduct/ListProductViewModel.java
- app/src/main/java/com/framgia/forder/screen/mainpage/product/ItemProductViewModel.java
- app/src/main/java/com/framgia/forder/screen/productdetail/ProductDetailViewModel.java
- app/src/main/java/com/framgia/forder/utils/Utils.java
- app/src/main/res/layout/fragment_listproduct.xml
- app/src/main/res/layout/fragment_product_detail.xml
- app/src/main/res/layout/item_list_product.xml
[Sprint Maintain] Feature Allow Order In Time
Link redmine : https://dev.framgia.com/redmine/issues/126107
Effect: N/A
> [Sprint Maintain] Feature Allow Order In Time

- app/src/main/java/com/framgia/forder/screen/createProduct/CreateProductContract.java
- app/src/main/java/com/framgia/forder/screen/createProduct/CreateProductPresenter.java
- app/src/main/java/com/framgia/forder/screen/createProduct/CreateProductViewModel.java
- app/src/main/java/com/framgia/forder/screen/mainpage/product/ItemProductViewModel.java
- app/src/main/java/com/framgia/forder/screen/updateProduct/UpdateProductContract.java
- app/src/main/java/com/framgia/forder/screen/updateProduct/UpdateProductPresenter.java
- app/src/main/java/com/framgia/forder/screen/updateProduct/UpdateProductViewModel.java
[Sprint Maintain] Fix Progressbar Edit Create Product 
Link redmine : https://dev.framgia.com/redmine/issues/126146
Effect: N/A
> [Sprint Maintain] Fix Progressbar Edit Create Product

- app/src/main/java/com/framgia/forder/data/source/remote/api/service/ServiceClient.java
- app/src/main/java/com/framgia/forder/screen/listshop/ListShopContract.java
- app/src/main/java/com/framgia/forder/screen/listshop/ListShopPresenter.java
- app/src/main/java/com/framgia/forder/screen/listshop/ListShopViewModel.java
- app/src/main/java/com/framgia/forder/screen/mainpage/MainPageContract.java
- app/src/main/java/com/framgia/forder/screen/mainpage/MainPageFragment.java
- app/src/main/java/com/framgia/forder/screen/mainpage/MainPagePresenter.java
- app/src/main/java/com/framgia/forder/screen/mainpage/MainPageViewModel.java
- app/src/main/res/layout/fragment_list_shop.xml
[Sprint Maintain] Add Progress & Fix List All Shop
Link redmine : https://dev.framgia.com/redmine/issues/126102
Effect: N/A
> [Sprint Maintain] Add Progress & Fix List All Shop

- app/src/main/java/com/framgia/forder/screen/shopindomain/ShopInDomainContract.java
- app/src/main/java/com/framgia/forder/screen/shopindomain/ShopInDomainPresenter.java
- app/src/main/java/com/framgia/forder/screen/shopindomain/ShopInDomainViewModel.java
- app/src/main/java/com/framgia/forder/screen/userindomain/UserInDomainContract.java
- app/src/main/java/com/framgia/forder/screen/userindomain/UserInDomainPresenter.java
- app/src/main/java/com/framgia/forder/screen/userindomain/UserInDomainViewModel.java
- app/src/main/res/layout/fragment_shop_in_domain.xml
- app/src/main/res/layout/fragment_user_in_domain.xml
[Sprint Maintain] Add Progressbar User In Domain And Shop In Domain
Link redmine : https://dev.framgia.com/redmine/issues/126179
Effect: N/A
> [Sprint Maintain] Add Progressbar User In Domain And Shop In Domain

- app/src/main/java/com/framgia/forder/screen/createshop/CreateshopContract.java
- app/src/main/java/com/framgia/forder/screen/createshop/CreateshopPresenter.java
- app/src/main/java/com/framgia/forder/screen/createshop/CreateshopViewModel.java
- app/src/main/java/com/framgia/forder/screen/domainmanagement/editdomain/EditdomainViewModel.java
- app/src/main/java/com/framgia/forder/screen/productdetail/ProductDetailViewModel.java
- app/src/main/res/layout/fragment_edit_domain.xml
- app/src/main/res/layout/item_product.xml
- app/src/main/res/menu/menu_domain_management.xml
- app/src/main/res/values/strings.xml
[Sprint Maintain] Fix Bug Change Status Domain And Add Progressbar In Create Shop
Link redmine : https://dev.framgia.com/redmine/issues/126278
Effect: N/A
> [Sprint Maintain] Fix Bug Change Status Domain And Add Progressbar In Create Shop

- app/src/main/java/com/framgia/forder/data/source/ProductDataSource.java
- app/src/main/java/com/framgia/forder/data/source/ProductRepository.java
- app/src/main/java/com/framgia/forder/data/source/remote/ProductRemoteDataSource.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/service/FOrderApi.java
- app/src/main/java/com/framgia/forder/screen/shopinfo/productshopinfo/ProductShopInfoContract.java
- app/src/main/java/com/framgia/forder/screen/shopinfo/productshopinfo/ProductShopInfoFragment.java
- app/src/main/java/com/framgia/forder/screen/shopinfo/productshopinfo/ProductShopInfoPresenter.java
- app/src/main/java/com/framgia/forder/screen/shopinfo/productshopinfo/ProductShopInfoViewModel.java
- app/src/main/res/layout/fragment_product_shop_info.xml
[Sprint Maintain] Feature Delete Product ShopInfo
Link redmine : https://dev.framgia.com/redmine/issues/126326
Effect: N/A
> [Sprint Maintain] Feature Delete Product ShopInfo

- app/src/main/java/com/framgia/forder/data/source/ProductDataSource.java
- app/src/main/java/com/framgia/forder/data/source/ProductRepository.java
- app/src/main/java/com/framgia/forder/data/source/remote/ProductRemoteDataSource.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/service/FOrderApi.java
- app/src/main/java/com/framgia/forder/screen/shopinfo/productshopinfo/ItemProductShopInformationViewModel.java
- app/src/main/java/com/framgia/forder/screen/shopinfo/productshopinfo/ProductShopInfoContract.java
- app/src/main/java/com/framgia/forder/screen/shopinfo/productshopinfo/ProductShopInfoPresenter.java
- app/src/main/java/com/framgia/forder/screen/shopinfo/productshopinfo/ProductShopInfoViewModel.java
- app/src/main/java/com/framgia/forder/screen/shopinfo/productshopinfo/UpdateProductListener.java
- app/src/main/res/layout/item_product_shop_info.xml
[Sprint Maintain] Feature Delete Product ShopInfo Next
Link redmine : https://dev.framgia.com/redmine/issues/126326
Effect: N/A
> [Sprint Maintain] Feature Delete Product ShopInfo Next

- app/src/main/java/com/framgia/forder/data/source/ShopDataSource.java
- app/src/main/java/com/framgia/forder/data/source/ShopRepository.java
- app/src/main/java/com/framgia/forder/data/source/local/MyFirebaseMessagingService.java
- app/src/main/java/com/framgia/forder/data/source/remote/ShopRemoteDataSource.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/service/FOrderApi.java
- app/src/main/java/com/framgia/forder/screen/main/MainViewModel.java
- app/src/main/java/com/framgia/forder/screen/shopmanagement/ShopManagementContract.java
- app/src/main/java/com/framgia/forder/screen/shopmanagement/ShopManagementFragment.java
- app/src/main/java/com/framgia/forder/screen/shopmanagement/ShopManagementPresenter.java
- app/src/main/java/com/framgia/forder/screen/shopmanagement/ShopManagementViewModel.java
[Sprint Maintain] Edit Notification & Change Domain & Update Status Shop Manangement
Link redmine : https://dev.framgia.com/redmine/issues/126102
Effect: N/A
> [Sprint Maintain] Edit Notification & Change Domain & Update Status Shop Manangement

- app/src/main/java/com/framgia/forder/data/source/ShopDataSource.java
- app/src/main/java/com/framgia/forder/data/source/ShopRepository.java
- app/src/main/java/com/framgia/forder/data/source/local/MyFirebaseMessagingService.java
- app/src/main/java/com/framgia/forder/data/source/remote/ShopRemoteDataSource.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/service/FOrderApi.java
- app/src/main/java/com/framgia/forder/screen/shopmanagement/ItemShopManagementViewModel.java
- app/src/main/java/com/framgia/forder/screen/shopmanagement/ListShopManagementAdapter.java
- app/src/main/java/com/framgia/forder/screen/shopmanagement/ShopManagementContract.java
- app/src/main/java/com/framgia/forder/screen/shopmanagement/ShopManagementPresenter.java
- app/src/main/java/com/framgia/forder/utils/Constant.java
[Sprint Maintain] Feature On - Off Shop Management
Link redmine : https://dev.framgia.com/redmine/issues/126102
Effect: N/A
> [Sprint Maintain] Feature On - Off Shop Management

- app/src/main/java/com/framgia/forder/data/source/ProductDataSource.java
- app/src/main/java/com/framgia/forder/data/source/ProductRepository.java
- app/src/main/java/com/framgia/forder/data/source/remote/ProductRemoteDataSource.java
- app/src/main/java/com/framgia/forder/screen/productdetail/ProductDetailContract.java
- app/src/main/java/com/framgia/forder/screen/productdetail/ProductDetailPresenter.java
- app/src/main/java/com/framgia/forder/screen/productdetail/ProductDetailViewModel.java
- app/src/main/java/com/framgia/forder/screen/productdetail/adapter/CommentAdapter.java
- app/src/main/java/com/framgia/forder/screen/productdetail/adapter/ItemUserViewModel.java
- app/src/main/res/drawable/ic_circle.xml
- app/src/main/res/layout/item_comment_product.xml
[Sprint Maintain] Create UI & Logic Delete Comment
Link redmine : https://dev.framgia.com/redmine/issues/125130
Effect: N/A
> [Sprint Maintain] Create UI & Logic Delete Comment

- app/src/main/java/com/framgia/forder/screen/ordershop/OrderShopContract.java
- app/src/main/java/com/framgia/forder/screen/ordershop/OrderShopPresenter.java
- app/src/main/java/com/framgia/forder/screen/ordershop/OrderShopViewModel.java
- app/src/main/java/com/framgia/forder/screen/quickorder/QuickOrderViewModel.java
- app/src/main/java/com/framgia/forder/screen/shopinfo/productshopinfo/ProductShopInfoViewModel.java
- app/src/main/res/layout/fragment_ordershop.xml
[Sprint Maintain] Feature Show List Accept Order Next
Link redmine : https://dev.framgia.com/redmine/issues/126496
Effect: N/A
> [Sprint Maintain] Feature Show List Accept Order Next

- app/src/main/java/com/framgia/forder/data/model/OwnerShop.java
- app/src/main/java/com/framgia/forder/data/model/ShopInDomain.java
- app/src/main/java/com/framgia/forder/screen/managerinshop/ItemManagerInShopViewModel.java
- app/src/main/java/com/framgia/forder/screen/shopindomain/ItemShopInDomainViewModel.java
- app/src/main/res/layout/item_manager_in_shop.xml
- app/src/main/res/layout/item_shop_in_domain.xml
- app/src/main/res/values/strings.xml
[Sprint Maintain] Fix Logic Shop In Domain
Link redmine : https://dev.framgia.com/redmine/issues/126726
Effect: N/A
> [Sprint Maintain] Fix Logic Shop In Domain

- app/src/main/java/com/framgia/forder/data/source/remote/api/request/UpdateProfileRequest.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/response/UpdateProfileResponse.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/service/FOrderApi.java
- app/src/main/java/com/framgia/forder/screen/profilepage/updateprofile/UpdateProfileContract.java
- app/src/main/java/com/framgia/forder/screen/profilepage/updateprofile/UpdateProfileFragment.java
- app/src/main/java/com/framgia/forder/screen/profilepage/updateprofile/UpdateProfilePresenter.java
- app/src/main/java/com/framgia/forder/screen/profilepage/updateprofile/UpdateProfileViewModel.java
- app/src/main/res/layout/fragment_profile_update.xml
[Sprint Maintain] Fix Logic Update Profile User
Link redmine : https://dev.framgia.com/redmine/issues/126854
Effect: N/A
> [Sprint Maintain] Fix Logic Update Profile User

- app/src/main/java/com/framgia/forder/data/model/OrderDetail.java
- app/src/main/java/com/framgia/forder/screen/ordershop/OrderShopViewModel.java
- app/src/main/java/com/framgia/forder/screen/productdetail/ProductDetailContract.java
- app/src/main/java/com/framgia/forder/screen/productdetail/ProductDetailPresenter.java
- app/src/main/java/com/framgia/forder/screen/productdetail/ProductDetailViewModel.java
- app/src/main/java/com/framgia/forder/screen/profilepage/ProfilePageViewModel.java
- app/src/main/java/com/framgia/forder/screen/profilepage/profiledetail/ProfileDetailViewModel.java
- app/src/main/res/layout/fragment_profile.xml
- app/src/main/res/layout/fragment_profile_detail.xml
[Sprint Maintain] Fix Logic Profile & Detail, Logic List Accept Order
Link redmine : https://dev.framgia.com/redmine/issues/126990
Effect: N/A
> [Sprint Maintain] Fix Logic Profile & Detail, Logic List Accept Order

- app/src/main/java/com/framgia/forder/data/source/DomainDataSource.java
- app/src/main/java/com/framgia/forder/data/source/DomainRepository.java
- app/src/main/java/com/framgia/forder/data/source/remote/DomainRemoteDataSource.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/request/AddUserInDomainRequest.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/service/FOrderApi.java
- app/src/main/java/com/framgia/forder/screen/adduserindomain/AddUserInDomainContract.java
- app/src/main/java/com/framgia/forder/screen/adduserindomain/AddUserInDomainFragment.java
- app/src/main/java/com/framgia/forder/screen/adduserindomain/AddUserInDomainPresenter.java
- app/src/main/java/com/framgia/forder/screen/adduserindomain/AddUserInDomainViewModel.java
- app/src/main/res/layout/fragment_add_user_in_domain.xml
[Sprint 6] Feature ui add user in domain
Effect: N/A
> [Sprint Maintain] Feature ui add user in domain

- app/src/main/java/com/framgia/forder/data/source/remote/api/request/AddUserInDomainRequest.java
- app/src/main/java/com/framgia/forder/screen/adduserindomain/AddUserInDomainAdapter.java
- app/src/main/java/com/framgia/forder/screen/adduserindomain/AddUserInDomainContract.java
- app/src/main/java/com/framgia/forder/screen/adduserindomain/AddUserInDomainFragment.java
- app/src/main/java/com/framgia/forder/screen/adduserindomain/AddUserInDomainPresenter.java
- app/src/main/java/com/framgia/forder/screen/adduserindomain/AddUserInDomainViewModel.java
- app/src/main/java/com/framgia/forder/screen/adduserindomain/ItemAddUserInDomainViewModel.java
- app/src/main/res/layout/fragment_add_user_in_domain.xml
- app/src/main/res/layout/item_add_user_in_domain.xml
- app/src/main/res/values/strings.xml
[Sprint 6] Feature Logic Add User In Domain
Effect: N/A
> [Sprint 6] Feature Logic Add User In Domain

- app/src/main/java/com/framgia/forder/screen/userindomain/ItemUserInDomainViewModel.java
- app/src/main/java/com/framgia/forder/screen/userindomain/UserInDomainContract.java
- app/src/main/java/com/framgia/forder/screen/userindomain/UserInDomainPresenter.java
- app/src/main/java/com/framgia/forder/screen/userindomain/UserInDomainViewModel.java
- app/src/main/res/layout/fragment_user_in_domain.xml
[Sprint 6] Feature Logic Add User In Domain Next
Effect: N/A
> [Sprint 6] Feature Logic Add User In Domain Next

- app/src/main/java/com/framgia/forder/screen/cart/ShoppingCartFragment.java
- app/src/main/java/com/framgia/forder/screen/cart/ShoppingCartViewModel.java
- app/src/main/java/com/framgia/forder/screen/listProduct/ListProductFragment.java
- app/src/main/java/com/framgia/forder/screen/listProduct/ListProductViewModel.java
- app/src/main/java/com/framgia/forder/screen/main/LoadCartListener.java
- app/src/main/java/com/framgia/forder/screen/main/MainActivity.java
- app/src/main/java/com/framgia/forder/screen/main/MainContract.java
- app/src/main/java/com/framgia/forder/screen/main/MainPresenter.java
- app/src/main/java/com/framgia/forder/screen/main/MainViewModel.java
- app/src/main/res/layout/layout_footer.xml
[Sprint Maintain] Fix UI Footer
Link redmine : https://dev.framgia.com/redmine/issues/127320
Effect: N/A
> [Sprint Maintain] Fix UI Footer

- app/src/main/java/com/framgia/forder/screen/mainpage/MainPageFragment.java
- app/src/main/java/com/framgia/forder/screen/mainpage/MainPageViewModel.java
- app/src/main/java/com/framgia/forder/screen/productdetail/ProductDetailFragment.java
- app/src/main/java/com/framgia/forder/screen/productdetail/ProductDetailViewModel.java
[Sprint Maintain] Fix Logic Footer
Link redmine : https://dev.framgia.com/redmine/issues/127320
Effect: N/A
> [Sprint Maintain] Fix Logic Footer

- app/src/main/java/com/framgia/forder/data/source/DomainDataSource.java
- app/src/main/java/com/framgia/forder/data/source/DomainRepository.java
- app/src/main/java/com/framgia/forder/data/source/remote/DomainRemoteDataSource.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/response/DomainToRequestShopResponse.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/service/FOrderApi.java
- app/src/main/java/com/framgia/forder/screen/cart/ShoppingCartViewModel.java
[Sprint Maintain] Fix Logic Footer
Link redmine : https://dev.framgia.com/redmine/issues/127414
Effect: N/A
> [Sprint Maintain] Fix Logic Load List Domain ShopInfo

- app/src/main/java/com/framgia/forder/data/source/remote/api/response/DomainToRequestShopResponse.java
- app/src/main/java/com/framgia/forder/screen/shopinfo/ShopinfoContract.java
- app/src/main/java/com/framgia/forder/screen/shopinfo/ShopinfoFragment.java
- app/src/main/java/com/framgia/forder/screen/shopinfo/ShopinfoPresenter.java
- app/src/main/java/com/framgia/forder/screen/shopinfo/ShopinfoViewModel.java
- app/src/main/java/com/framgia/forder/screen/shopinfo/listdomain/ItemListDomainViewModel.java
- app/src/main/java/com/framgia/forder/screen/shopinfo/listdomain/ListDomainAdapter.java
- app/src/main/res/layout/fragment_shopinfo.xml
- app/src/main/res/values/strings.xml
[Sprint Maintain] Fix Logic Load List Domain ShopInfo Next
Link redmine : https://dev.framgia.com/redmine/issues/127414
Effect: N/A
> [Sprint Maintain] Fix Logic Load List Domain ShopInfo Next

- app/src/main/java/com/framgia/forder/data/source/CategoryDataSource.java
- app/src/main/java/com/framgia/forder/data/source/CategoryRepository.java
- app/src/main/java/com/framgia/forder/data/source/remote/CategoryRemoteDataSource.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/service/FOrderApi.java
- app/src/main/java/com/framgia/forder/screen/createProduct/CreateProductPresenter.java
- app/src/main/java/com/framgia/forder/screen/createProduct/CreateProductViewModel.java
- app/src/main/java/com/framgia/forder/screen/updateProduct/UpdateProductPresenter.java
- app/src/main/java/com/framgia/forder/screen/updateProduct/UpdateProductViewModel.java
- app/src/main/res/layout/fragment_create_product.xml
- app/src/main/res/layout/fragment_update_product.xml
[Sprint Maintain] Fix List Category In Create & Update Product
Link redmine : https://dev.framgia.com/redmine/issues/127459
Effect: N/A
> [Sprint Maintain] Fix List Category In Create & Update Product

- app/src/main/java/com/framgia/forder/screen/shopindomain/ItemShopInDomainViewModel.java
- app/src/main/java/com/framgia/forder/screen/shopindomain/ShopInDomainAdapter.java
- app/src/main/java/com/framgia/forder/screen/shopindomain/ShopInDomainViewModel.java
- app/src/main/res/layout/fragment_list_accept_order.xml
- app/src/main/res/layout/fragment_ordershop.xml
- app/src/main/res/layout/item_user_order.xml
[Sprint Maintain] Feature Role In Shop Domain
Link redmine : https://dev.framgia.com/redmine/issues/127629
Effect: N/A
> [Sprint Maintain] Feature Role In Shop Domain

- app/src/main/java/com/framgia/forder/data/source/ProductDataSource.java
- app/src/main/java/com/framgia/forder/data/source/ProductRepository.java
- app/src/main/java/com/framgia/forder/data/source/remote/ProductRemoteDataSource.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/service/FOrderApi.java
- app/src/main/java/com/framgia/forder/screen/listproductbycategory/ListProductByCategoryContract.java
- app/src/main/java/com/framgia/forder/screen/listproductbycategory/ListProductByCategoryFragment.java
- app/src/main/java/com/framgia/forder/screen/listproductbycategory/ListProductByCategoryPresenter.java
- app/src/main/java/com/framgia/forder/screen/listproductbycategory/ListProductByCategoryViewModel.java
- app/src/main/res/layout/fragment_list_product_by_category.xml
- app/src/main/res/layout/item_category.xml
[Sprint Maintain] Feature Load List Product By Category
Link redmine : https://dev.framgia.com/redmine/issues/127675
Effect: N/A
> [Sprint Maintain] Feature Load List Product By Category

- app/src/main/java/com/framgia/forder/screen/main/ChangeDomainListener.java
- app/src/main/java/com/framgia/forder/screen/main/MainActivity.java
- app/src/main/java/com/framgia/forder/screen/main/MainContainerFragment.java
- app/src/main/java/com/framgia/forder/screen/main/MainContract.java
- app/src/main/java/com/framgia/forder/screen/main/MainViewModel.java
- app/src/main/java/com/framgia/forder/screen/mainpage/MainPageContract.java
- app/src/main/java/com/framgia/forder/screen/mainpage/MainPageFragment.java
- app/src/main/java/com/framgia/forder/screen/mainpage/MainPageViewModel.java
- app/src/main/java/com/framgia/forder/screen/mainpage/shop/ShopPageFragment.java
- app/src/main/res/layout/layout_footer.xml
[Sprint Maintain] Feature Load List Product By Category Next
Link redmine : https://dev.framgia.com/redmine/issues/127675
Effect: N/A
> [Sprint Maintain] Feature Load List Product By Category Next, Delete TabHost In Home & Fix Logic Change Domain

- app/src/main/java/com/framgia/forder/data/model/User.java
- app/src/main/java/com/framgia/forder/screen/managerdetail/ManagerDetailFragment.java
- app/src/main/java/com/framgia/forder/screen/managerdetail/ManagerDetailViewModel.java
- app/src/main/java/com/framgia/forder/screen/profilepage/profiledetail/ProfileDetailViewModel.java
- app/src/main/java/com/framgia/forder/utils/StatusCode.java
- app/src/main/res/layout/fragment_managerdetail.xml
- app/src/main/res/layout/fragment_profile_detail.xml
- app/src/main/res/layout/fragment_profile_update.xml
Fix UI Profile Detail & Manager Detail
Link redmine: https://dev.framgia.com/redmine/issues/127788
> [Sprint Maintain] Fix UI Profile Detail & Manager Detail

- app/src/main/java/com/framgia/forder/screen/addmanagershop/AddManagerShopContract.java
- app/src/main/java/com/framgia/forder/screen/addmanagershop/AddManagerShopFragment.java
- app/src/main/java/com/framgia/forder/screen/addmanagershop/AddManagerShopPresenter.java
- app/src/main/java/com/framgia/forder/screen/addmanagershop/AddManagerShopViewModel.java
- app/src/main/java/com/framgia/forder/screen/addmanagershop/ItemAddManagerInShopViewModel.java
- app/src/main/res/drawable/ic_add_circle.xml
- app/src/main/res/layout/fragment_add_manager_shop.xml
- app/src/main/res/layout/fragment_shopinfo.xml
- app/src/main/res/layout/item_manager.xml
- app/src/main/res/values/strings.xml
Feature Add Manager In Shop
Link redmine: https://dev.framgia.com/redmine/issues/128070
> [Sprint Maintain] Feature Add Manager In Shop

- app/src/main/java/com/framgia/forder/data/model/Notification.java
- app/src/main/java/com/framgia/forder/data/source/NotificationRepository.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/response/NotificationResponse.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/service/FOrderApi.java
- app/src/main/java/com/framgia/forder/screen/notification/NotificationPageViewModel.java
- app/src/main/java/com/framgia/forder/utils/StatusCode.java
- app/src/main/res/layout/item_list_notification.xml
Feature Get List Notification
Link redmine: https://dev.framgia.com/redmine/issues/128138
> [Sprint Maintain] Feature Get List Notification

- app/src/main/java/com/framgia/forder/screen/addmanagershop/AddManagerShopAdapter.java
- app/src/main/java/com/framgia/forder/screen/addmanagershop/AddManagerShopContract.java
- app/src/main/java/com/framgia/forder/screen/addmanagershop/AddManagerShopFragment.java
- app/src/main/java/com/framgia/forder/screen/addmanagershop/AddManagerShopPresenter.java
- app/src/main/java/com/framgia/forder/screen/addmanagershop/AddManagerShopViewModel.java
- app/src/main/java/com/framgia/forder/screen/addmanagershop/ItemAddManagerInShopViewModel.java
- app/src/main/java/com/framgia/forder/screen/shopinfo/ShopinfoViewModel.java
- app/src/main/res/layout/fragment_add_manager_shop.xml
- app/src/main/res/layout/fragment_shopinfo.xml
- app/src/main/res/layout/item_add_manager_in_shop.xml
Feature Get List User In Domain
Link redmine: https://dev.framgia.com/redmine/issues/128125
> [Sprint Maintain] Feature Get List User In Domain

- app/src/main/java/com/framgia/forder/data/model/User.java
- app/src/main/java/com/framgia/forder/data/source/ShopDataSource.java
- app/src/main/java/com/framgia/forder/data/source/ShopRepository.java
- app/src/main/java/com/framgia/forder/data/source/remote/ShopRemoteDataSource.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/service/FOrderApi.java
- app/src/main/java/com/framgia/forder/screen/requestshopindomain/ItemRequestShopInDomain.java
- app/src/main/java/com/framgia/forder/screen/requestshopindomain/RequestShopInDomainAdapter.java
- app/src/main/java/com/framgia/forder/screen/requestshopindomain/RequestShopInDomainFragment.java
- app/src/main/java/com/framgia/forder/screen/shopindomain/ShopInDomainContract.java
- app/src/main/java/com/framgia/forder/screen/shopindomain/ShopInDomainPresenter.java
- app/src/main/java/com/framgia/forder/screen/shopindomain/ShopInDomainViewModel.java
[Sprint Maintain] Feature Create Logic List Shop Request 
Link redmine : https://dev.framgia.com/redmine/issues/128125
Effect: N/A
> [Sprint Maintain] Feature Create Logic List Shop Request 

- app/src/main/java/com/framgia/forder/screen/requestshopindomain/RequestShopInDomainContract.java
- app/src/main/java/com/framgia/forder/screen/requestshopindomain/RequestShopInDomainFragment.java
- app/src/main/java/com/framgia/forder/screen/requestshopindomain/RequestShopInDomainPresenter.java
- app/src/main/java/com/framgia/forder/screen/requestshopindomain/RequestShopInDomainViewModel.java
- app/src/main/res/layout/fragment_request_shop_in_domain.xml
- app/src/main/res/layout/fragment_shop_in_domain.xml
- app/src/main/res/layout/item_request_shop_in_domain.xml
[Sprint Maintain] Feature Logic List Shop Request Next
Link redmine : https://dev.framgia.com/redmine/issues/128125
Effect: N/A
> [Sprint Maintain] Feature Logic List Shop Request Next

- app/src/main/java/com/framgia/forder/data/source/remote/api/service/FOrderApi.java
- app/src/main/java/com/framgia/forder/screen/addmanagershop/AddManagerShopAdapter.java
- app/src/main/java/com/framgia/forder/screen/addmanagershop/AddManagerShopContract.java
- app/src/main/java/com/framgia/forder/screen/addmanagershop/AddManagerShopFragment.java
- app/src/main/java/com/framgia/forder/screen/addmanagershop/AddManagerShopPresenter.java
- app/src/main/java/com/framgia/forder/screen/addmanagershop/AddManagerShopViewModel.java
- app/src/main/java/com/framgia/forder/screen/addmanagershop/ItemAddManagerInShopViewModel.java
- app/src/main/res/layout/item_add_manager_in_shop.xml
- app/src/main/res/values/strings.xml
Feature Add Manager Continue
Link redmine :https://dev.framgia.com/redmine/issues/128070
> [Sprint Maintain] Feature Add Manager Continue

- app/src/main/java/com/framgia/forder/data/model/Order.java
- app/src/main/java/com/framgia/forder/data/model/OrderDetail.java
- app/src/main/java/com/framgia/forder/screen/orderhistory/ItemHeaderOrderHistoryViewModel.java
- app/src/main/java/com/framgia/forder/utils/StatusCode.java
- app/src/main/res/drawable/button_green.xml
- app/src/main/res/layout/fragment_order_history.xml
- app/src/main/res/layout/item_header_order_history.xml
- app/src/main/res/layout/item_order_history.xml
[Sprint Maintain] Fix UI Order History
Link redmine :https://dev.framgia.com/redmine/issues/128462
> [Sprint Maintain] Fix UI Order History

- app/src/main/java/com/framgia/forder/screen/domainmanagement/DomainManagementAdapter.java
- app/src/main/java/com/framgia/forder/screen/domainmanagement/ItemDomainManagementViewModel.java
- app/src/main/java/com/framgia/forder/screen/orderhistory/OrderHistoryContract.java
- app/src/main/java/com/framgia/forder/screen/orderhistory/OrderHistoryFragment.java
- app/src/main/java/com/framgia/forder/screen/orderhistory/OrderHistoryPresenter.java
- app/src/main/java/com/framgia/forder/screen/orderhistory/OrderHistoryViewModel.java
- app/src/main/res/values-vi/strings.xml
- app/src/main/res/values/strings.xml
[Sprint Maintain] Fix UI Order History Next
Link redmine :https://dev.framgia.com/redmine/issues/128462
> [Sprint Maintain] Fix UI Order History Next

- app/src/main/java/com/framgia/forder/data/model/Product.java
- app/src/main/java/com/framgia/forder/screen/notification/ItemNotificationViewModel.java
- app/src/main/java/com/framgia/forder/screen/notification/NotificationPageAdapter.java
- app/src/main/java/com/framgia/forder/screen/notification/NotificationPageFragment.java
- app/src/main/java/com/framgia/forder/screen/notification/NotificationPageViewModel.java
- app/src/main/java/com/framgia/forder/utils/StatusCode.java
- app/src/main/res/layout/item_list_notification.xml
Event Item Click Notification
Link redmine : https://dev.framgia.com/redmine/issues/128138
> [Sprint Maitain] Event ItemClick Notification

- app/src/main/java/com/framgia/forder/screen/profilepage/profiledetail/ProfileDetailPresenter.java
- app/src/main/java/com/framgia/forder/screen/profilepage/updateprofile/UpdateProfilePresenter.java
- app/src/main/res/layout/fragment_profile_update.xml
[Sprint Maintain] Feature Fix Logic Update Profile
Link redmine :https://dev.framgia.com/redmine/issues/128885
> [Sprint Maintain] 	Feature Fix Logic Update Profile

- app/src/main/java/com/framgia/forder/screen/addtocart/AddToCartContract.java
- app/src/main/java/com/framgia/forder/screen/addtocart/AddToCartFragment.java
- app/src/main/java/com/framgia/forder/screen/addtocart/AddToCartPresenter.java
- app/src/main/java/com/framgia/forder/screen/addtocart/AddToCartViewModel.java
- app/src/main/java/com/framgia/forder/screen/listProduct/ListProductContract.java
- app/src/main/java/com/framgia/forder/screen/listProduct/ListProductPresenter.java
- app/src/main/java/com/framgia/forder/screen/listProduct/ListProductViewModel.java
- app/src/main/java/com/framgia/forder/utils/navigator/Navigator.java
- app/src/main/res/drawable/border_button_continue.xml
- app/src/main/res/drawable/border_button_order.xml
- app/src/main/res/layout/fragment_add_to_cart.xml
Feature Logic Add To Cart
Link redmine: https://dev.framgia.com/redmine/issues/134793
> [Sprint 1]Feature Logic Add To Cart

- app/src/main/java/com/framgia/forder/screen/listProduct/ListProductViewModel.java
- app/src/main/java/com/framgia/forder/screen/listproductbycategory/ListProductByCategoryContract.java
- app/src/main/java/com/framgia/forder/screen/listproductbycategory/ListProductByCategoryPresenter.java
- app/src/main/java/com/framgia/forder/screen/listproductbycategory/ListProductByCategoryViewModel.java
- app/src/main/java/com/framgia/forder/screen/mainpage/MainPageContract.java
- app/src/main/java/com/framgia/forder/screen/mainpage/MainPagePresenter.java
- app/src/main/java/com/framgia/forder/screen/mainpage/MainPageViewModel.java
- app/src/main/java/com/framgia/forder/screen/mainpage/ordercart/BaseOrderCartViewModel.java
- app/src/main/java/com/framgia/forder/screen/productdetail/ProductDetailContract.java
- app/src/main/java/com/framgia/forder/screen/productdetail/ProductDetailPresenter.java
- app/src/main/java/com/framgia/forder/screen/productdetail/ProductDetailViewModel.java
- app/src/main/java/com/framgia/forder/screen/searchproduct/ProductSearchResultContract.java
- app/src/main/java/com/framgia/forder/screen/searchproduct/ProductSearchResultPresenter.java
- app/src/main/java/com/framgia/forder/screen/searchproduct/ProductSearchResultViewModel.java
Feature Logic Add To Cart In Another Screen
Link redmine: https://dev.framgia.com/redmine/issues/134793
> [Sprint 1]Feature Logic Add To Cart In Another Screen

- app/src/main/java/com/framgia/forder/data/source/ProductDataSource.java
- app/src/main/java/com/framgia/forder/data/source/ProductRepository.java
- app/src/main/java/com/framgia/forder/data/source/remote/ProductRemoteDataSource.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/service/FOrderApi.java
- app/src/main/java/com/framgia/forder/screen/listProduct/ListProductContract.java
- app/src/main/java/com/framgia/forder/screen/listProduct/ListProductPresenter.java
- app/src/main/java/com/framgia/forder/screen/listProduct/ListProductViewModel.java
- app/src/main/res/layout/fragment_listproduct.xml
- app/src/main/res/values/array.xml
- app/src/main/res/values/strings.xml
Logic Fillter Product In List
Link: https://dev.framgia.com/redmine/issues/134794
> [Sprint 1]Logic Fillter Product In List

- app/src/main/java/com/framgia/forder/data/source/NotificationSettingDataSource.java
- app/src/main/java/com/framgia/forder/data/source/NotificationSettingRepository.java
- app/src/main/java/com/framgia/forder/data/source/remote/NotificationSettingRemoteDataSource.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/request/NotificationSettingRequest.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/response/NotificationSettingResponse.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/service/FOrderApi.java
- app/src/main/java/com/framgia/forder/screen/notificationsetting/NotificationSettingContract.java
- app/src/main/java/com/framgia/forder/screen/notificationsetting/NotificationSettingFragment.java
- app/src/main/java/com/framgia/forder/screen/notificationsetting/NotificationSettingPresenter.java
- app/src/main/java/com/framgia/forder/screen/notificationsetting/NotificationSettingViewModel.java
- app/src/main/res/layout/fragment_notification_setting.xml
Logic Notification Setting
Link: https://dev.framgia.com/redmine/issues/134797
> [Sprint 2]Logic Notification Setting

- app/src/main/java/com/framgia/forder/data/source/ProductDataSource.java
- app/src/main/java/com/framgia/forder/data/source/ProductRepository.java
- app/src/main/java/com/framgia/forder/data/source/remote/ProductRemoteDataSource.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/service/FOrderApi.java
- app/src/main/java/com/framgia/forder/screen/listProduct/ListProductContract.java
- app/src/main/java/com/framgia/forder/screen/listProduct/ListProductPresenter.java
- app/src/main/java/com/framgia/forder/screen/listProduct/ListProductViewModel.java
- app/src/main/java/com/framgia/forder/screen/shopmanagement/ItemShopManagementViewModel.java
- app/src/main/java/com/framgia/forder/screen/shopmanagement/ShopManagementViewModel.java
Logic Fillter List Product Next & Fix Logic On/Off Shop
Link: https://dev.framgia.com/redmine/issues/134794
> [Sprint 1]Logic Fillter List Product Next & Fix Logic On/Off Shop

- app/src/main/java/com/framgia/forder/data/model/DomainManagement.java
- app/src/main/java/com/framgia/forder/data/model/RegisterDomain.java
- app/src/main/java/com/framgia/forder/data/source/DomainDataSource.java
- app/src/main/java/com/framgia/forder/data/source/DomainRepository.java
- app/src/main/java/com/framgia/forder/data/source/remote/DomainRemoteDataSource.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/service/FOrderApi.java
- app/src/main/java/com/framgia/forder/screen/domainmanagement/DomainManagementContract.java
- app/src/main/java/com/framgia/forder/screen/domainmanagement/DomainManagementPresenter.java
- app/src/main/java/com/framgia/forder/screen/domainmanagement/DomainManagementViewModel.java
- app/src/main/java/com/framgia/forder/screen/domainmanagement/adddomain/AddDomainListener.java
- app/src/main/java/com/framgia/forder/screen/domainmanagement/adddomain/AddDomainViewModel.java
- app/src/main/java/com/framgia/forder/screen/domainmanagement/editdomain/EditDomainListener.java
- app/src/main/java/com/framgia/forder/screen/domainmanagement/editdomain/EditdomainViewModel.java
- app/src/main/res/layout/fragment_add_domain.xml
- app/src/main/res/layout/fragment_edit_domain.xml
- app/src/main/res/values/strings.xml
Feature Add Chatwork In Create Update Domain
Link: https://dev.framgia.com/redmine/issues/134796
> [Sprint 2]Feature Add Chatwork In Create Update Domain

- app/src/main/java/com/framgia/forder/screen/orderhistoryshop/OrderHistoryShopFragment.java
- app/src/main/java/com/framgia/forder/screen/orderhistoryshop/OrderHistoryShopViewModel.java
- app/src/main/res/drawable/hyperlink_underline.xml
- app/src/main/res/layout/fragment_order_history_shop.xml
- app/src/main/res/values-vi/strings.xml
- app/src/main/res/values/array.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
Feature Create UI Fillter Order History 
Link: https://dev.framgia.com/redmine/issues/134800
> [Sprint 4]Feature Create UI Fillter Order History

- app/src/main/java/com/framgia/forder/data/model/OrderDetail.java
- app/src/main/java/com/framgia/forder/data/source/OrderDataSource.java
- app/src/main/java/com/framgia/forder/data/source/OrderRepository.java
- app/src/main/java/com/framgia/forder/data/source/remote/OrderRemoteDataSource.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/service/FOrderApi.java
- app/src/main/java/com/framgia/forder/screen/ordershop/OrderShopContract.java
- app/src/main/java/com/framgia/forder/screen/ordershop/OrderShopFragment.java
- app/src/main/java/com/framgia/forder/screen/ordershop/OrderShopPresenter.java
- app/src/main/java/com/framgia/forder/screen/ordershop/OrderShopViewModel.java
- app/src/main/java/com/framgia/forder/utils/Constant.java
- app/src/main/res/layout/fragment_ordershop.xml
Feature Logic Filter List Order
Link: https://dev.framgia.com/redmine/issues/134799
> [Sprint 3]Feature Logic Filter List Order

- app/src/main/java/com/framgia/forder/data/source/ShopDataSource.java
- app/src/main/java/com/framgia/forder/data/source/ShopRepository.java
- app/src/main/java/com/framgia/forder/data/source/remote/ShopRemoteDataSource.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/response/CheckFollowShopResponse.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/service/FOrderApi.java
- app/src/main/java/com/framgia/forder/screen/shopDetail/ShopDetailContract.java
- app/src/main/java/com/framgia/forder/screen/shopDetail/ShopDetailFragment.java
- app/src/main/java/com/framgia/forder/screen/shopDetail/ShopDetailPresenter.java
- app/src/main/java/com/framgia/forder/screen/shopDetail/ShopDetailViewModel.java
- app/src/main/res/layout/fragment_shop_detail.xml
Logic Follow And Rating Detail Shop
Link: https://dev.framgia.com/redmine/issues/134802
https://dev.framgia.com/redmine/issues/134801
> [Sprint 4]Logic Follow And Rating Detail Shop

- app/src/main/java/com/framgia/forder/screen/cart/ShoppingCartFragment.java
- app/src/main/java/com/framgia/forder/screen/cart/ShoppingCartViewModel.java
- app/src/main/java/com/framgia/forder/screen/main/LoadOrderHistoryListener.java
- app/src/main/java/com/framgia/forder/screen/main/MainActivity.java
- app/src/main/java/com/framgia/forder/screen/main/MainContract.java
- app/src/main/java/com/framgia/forder/screen/main/MainViewModel.java
- app/src/main/res/layout/fragment_listproduct.xml
Feature Move To OrderHistory Page When Order By Cart
> Feature Move To OrderHistory Page When Order By Cart Success

- app/src/main/java/com/framgia/forder/data/model/Suggestion.java
- app/src/main/java/com/framgia/forder/screen/cart/ShoppingCartViewModel.java
- app/src/main/java/com/framgia/forder/screen/mainpage/MainPagePresenter.java
- app/src/main/java/com/framgia/forder/screen/orderhistory/OrderHistoryFragment.java
- app/src/main/java/com/framgia/forder/screen/orderhistory/OrderHistoryPresenter.java
- app/src/main/java/com/framgia/forder/screen/searchpage/SearchContainerViewModel.java
- app/src/main/java/com/framgia/forder/screen/userindomain/UserInDomainViewModel.java
- app/src/main/java/com/framgia/forder/utils/binding/BindingUtils.java
- app/src/main/res/layout/fragment_main_page.xml
- app/src/main/res/layout/fragment_search_container.xml
- app/src/main/res/layout/fragment_user_in_domain.xml
Fix MainPage & Filter Order History & Role Of User In Domain
> Fix MainPage & Filter Order History & Role Of User In Domain

- app/src/main/java/com/framgia/forder/data/source/ShopDataSource.java
- app/src/main/java/com/framgia/forder/data/source/ShopRepository.java
- app/src/main/java/com/framgia/forder/data/source/remote/ShopRemoteDataSource.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/service/FOrderApi.java
- app/src/main/java/com/framgia/forder/screen/cart/ShoppingCartViewModel.java
- app/src/main/java/com/framgia/forder/screen/mainpage/MainPageFragment.java
- app/src/main/java/com/framgia/forder/screen/mainpage/MainPagePresenter.java
- app/src/main/java/com/framgia/forder/screen/mainpage/shop/ShopPageAdapter.java
- app/src/main/java/com/framgia/forder/screen/mainpage/shop/ShopPageViewModel.java
- app/src/main/java/com/framgia/forder/screen/notification/NotificationPageViewModel.java
- app/src/main/java/com/framgia/forder/screen/ordershop/OrderShopViewModel.java
- app/src/main/java/com/framgia/forder/screen/requestshopindomain/ItemRequestShopInDomain.java
- app/src/main/java/com/framgia/forder/screen/shopindomain/ShopInDomainContract.java
- app/src/main/java/com/framgia/forder/screen/shopindomain/ShopInDomainPresenter.java
- app/src/main/java/com/framgia/forder/screen/shopindomain/ShopInDomainViewModel.java
- app/src/main/res/layout/fragment_main_page.xml
- app/src/main/res/layout/item_add_user_in_domain.xml
- app/src/main/res/layout/spinner_item_text_color_default.xml
- app/src/main/res/values-vi/strings.xml
- app/src/main/res/values/strings.xml
Fix Logic Cart
Load Api List Top Shop
Role Shop In Domain
https://dev.framgia.com/redmine/issues/139118
> Fix Logic Cart & Load Api List Top Shop & Role Shop In Domain

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/framgia/forder/data/event/NetWorkStateEvent.java
- app/src/main/java/com/framgia/forder/data/source/ProductRepository.java
- app/src/main/java/com/framgia/forder/data/source/remote/api/ConnectivityReceiver.java
- app/src/main/java/com/framgia/forder/screen/BaseActivity.java
- app/src/main/java/com/framgia/forder/screen/chooseDomain/ChooseDomainActivity.java
- app/src/main/java/com/framgia/forder/screen/forgotpassword/ForgotPasswordActivity.java
- app/src/main/java/com/framgia/forder/screen/listProduct/ListProductPresenter.java
- app/src/main/java/com/framgia/forder/screen/login/LoginActivity.java
- app/src/main/java/com/framgia/forder/screen/main/MainActivity.java
- app/src/main/java/com/framgia/forder/screen/main/MainContract.java
- app/src/main/java/com/framgia/forder/screen/main/MainPresenter.java
- app/src/main/java/com/framgia/forder/screen/main/MainViewModel.java
- app/src/main/java/com/framgia/forder/screen/mainpage/MainPagePresenter.java
- app/src/main/java/com/framgia/forder/screen/splash/SplashActivity.java
- app/src/main/res/values-vi/strings.xml
- app/src/main/res/values/strings.xml
- dependencies.gradle
Fix Ui Logic Main Page And Check Connection
> Fix Ui Logic Main Page And Check Connection

- app/src/main/java/com/framgia/forder/screen/chooseDomain/ChooseDomainPresenter.java
- app/src/main/java/com/framgia/forder/screen/domainmanagement/DomainManagementPresenter.java
- app/src/main/java/com/framgia/forder/screen/listProduct/ListProductPresenter.java
- app/src/main/java/com/framgia/forder/screen/listproductbycategory/ListProductByCategoryPresenter.java
- app/src/main/java/com/framgia/forder/screen/listshop/ListShopPresenter.java
- app/src/main/java/com/framgia/forder/screen/main/MainViewModel.java
- app/src/main/java/com/framgia/forder/screen/mainpage/MainPagePresenter.java
- app/src/main/java/com/framgia/forder/screen/ordershop/OrderShopPresenter.java
- app/src/main/java/com/framgia/forder/screen/ordershop/OrderShopViewModel.java
- app/src/main/java/com/framgia/forder/screen/shopindomain/ShopInDomainPresenter.java
- app/src/main/java/com/framgia/forder/screen/shopinfo/ShopinfoPresenter.java
- app/src/main/java/com/framgia/forder/screen/shopmanagement/ShopManagementPresenter.java
- app/src/main/res/layout/fragment_product_detail.xml
> Remove Progressbar

- app/src/main/java/com/framgia/forder/screen/listProduct/ListProductViewModel.java
- app/src/main/java/com/framgia/forder/screen/main/MainPresenter.java
- app/src/main/java/com/framgia/forder/screen/mainpage/MainPageViewModel.java
- app/src/main/java/com/framgia/forder/screen/mainpage/shop/ShopPageAdapter.java
- app/src/main/java/com/framgia/forder/screen/mainpage/shop/ShopPageViewModel.java
- app/src/main/java/com/framgia/forder/screen/ordershop/OrderShopViewModel.java
- app/src/main/java/com/framgia/forder/screen/requestshopindomain/RequestShopInDomainContract.java
- app/src/main/java/com/framgia/forder/screen/requestshopindomain/RequestShopInDomainPresenter.java
- app/src/main/java/com/framgia/forder/screen/requestshopindomain/RequestShopInDomainViewModel.java
- app/src/main/java/com/framgia/forder/screen/searchproduct/ProductSearchResultViewModel.java
- app/src/main/java/com/framgia/forder/screen/searchshop/ShopSearchResultViewModel.java
- app/src/main/java/com/framgia/forder/screen/shopindomain/ShopInDomainViewModel.java
- app/src/main/java/com/framgia/forder/screen/shopinfo/productshopinfo/ProductShopInfoContract.java
- app/src/main/java/com/framgia/forder/screen/shopinfo/productshopinfo/ProductShopInfoPresenter.java
- app/src/main/java/com/framgia/forder/screen/shopinfo/productshopinfo/ProductShopInfoViewModel.java
- app/src/main/res/layout/fragment_custom_slide_show.xml
- app/src/main/res/layout/fragment_listproduct.xml
- app/src/main/res/layout/fragment_main_page.xml
- app/src/main/res/layout/fragment_ordershop.xml
- app/src/main/res/layout/fragment_product_detail.xml
- app/src/main/res/layout/fragment_request_shop_in_domain.xml
- app/src/main/res/layout/fragment_shop_in_domain.xml
Add Nodata Screen & Fix Logic Change Domain
> Add Nodata Screen & Fix Logic Change Domain
